/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -I"C:\Program Files\nim\nim-0.18.0\lib" -o "C:\Users\Quinn Freedman\workspace\nim\smoke\src\nimcache\smoke_rectangle.o" "C:\Users\Quinn Freedman\workspace\nim\smoke\src\nimcache\smoke_rectangle.c" */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Rectangle_Nmh3mhZ3Bmv7pIjRzEqLVg tyObject_Rectangle_Nmh3mhZ3Bmv7pIjRzEqLVg;
typedef struct tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g;
struct tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g {
NI x;
NI y;
};
struct tyObject_Rectangle_Nmh3mhZ3Bmv7pIjRzEqLVg {
tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g upperLeft;
tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g lowerRight;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NI x, NI y, void* ClE_0);
void* ClE_0;
} tyProc_U9b2RsxBr7YW05GXUbwbFqw;
typedef N_CLOSURE_PTR(void, TM_20UnZOr9bevAwgKUDj8kGFA_10) (NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(tyObject_Rectangle_Nmh3mhZ3Bmv7pIjRzEqLVg, newRectangle_PZRoinI9cCau0UD1XjA81wA)(NI x, NI y, NI width, NI height);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g, v_g7Ok4O0iyLEmW9bny8ZknmA)(NI x, NI y);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g, upperLeft_0oeftziOMeBmYGOVY3fE7grectangle)(tyObject_Rectangle_Nmh3mhZ3Bmv7pIjRzEqLVg* self);
static N_INLINE(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g, lowerRight_0oeftziOMeBmYGOVY3fE7g_2rectangle)(tyObject_Rectangle_Nmh3mhZ3Bmv7pIjRzEqLVg* self);
static N_INLINE(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g, lowerLeft_0oeftziOMeBmYGOVY3fE7g_3rectangle)(tyObject_Rectangle_Nmh3mhZ3Bmv7pIjRzEqLVg* self);
static N_INLINE(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g, upperRight_0oeftziOMeBmYGOVY3fE7g_4rectangle)(tyObject_Rectangle_Nmh3mhZ3Bmv7pIjRzEqLVg* self);
static N_INLINE(NI, x_prTrI1MVo8MT9chBkL9c6JIArectangle)(tyObject_Rectangle_Nmh3mhZ3Bmv7pIjRzEqLVg* self);
static N_INLINE(NI, y_prTrI1MVo8MT9chBkL9c6JIA_2rectangle)(tyObject_Rectangle_Nmh3mhZ3Bmv7pIjRzEqLVg* self);
static N_INLINE(NI, width_prTrI1MVo8MT9chBkL9c6JIA_3rectangle)(tyObject_Rectangle_Nmh3mhZ3Bmv7pIjRzEqLVg* self);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(NI, height_prTrI1MVo8MT9chBkL9c6JIA_4rectangle)(tyObject_Rectangle_Nmh3mhZ3Bmv7pIjRzEqLVg* self);
N_LIB_PRIVATE N_NIMCALL(void, forEach_oCglDafOf4YskssJpz4WFA)(tyObject_Rectangle_Nmh3mhZ3Bmv7pIjRzEqLVg* self, tyProc_U9b2RsxBr7YW05GXUbwbFqw f);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NI, modInt)(NI a, NI b);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Rectangle_Nmh3mhZ3Bmv7pIjRzEqLVg, newRectangle_PZRoinI9cCau0UD1XjA81wA)(NI x, NI y, NI width, NI height) {
	tyObject_Rectangle_Nmh3mhZ3Bmv7pIjRzEqLVg result;
	NI TM_20UnZOr9bevAwgKUDj8kGFA_2;
	NI TM_20UnZOr9bevAwgKUDj8kGFA_3;
	nimfr_("newRectangle", "rectangle.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(8, "rectangle.nim");
	result.upperLeft = v_g7Ok4O0iyLEmW9bny8ZknmA(x, y);
	nimln_(9, "rectangle.nim");
	TM_20UnZOr9bevAwgKUDj8kGFA_2 = addInt(x, width);
	TM_20UnZOr9bevAwgKUDj8kGFA_3 = addInt(y, height);
	result.lowerRight = v_g7Ok4O0iyLEmW9bny8ZknmA((NI)(TM_20UnZOr9bevAwgKUDj8kGFA_2), (NI)(TM_20UnZOr9bevAwgKUDj8kGFA_3));
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g, upperLeft_0oeftziOMeBmYGOVY3fE7grectangle)(tyObject_Rectangle_Nmh3mhZ3Bmv7pIjRzEqLVg* self) {
	tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g result;
	nimfr_("upperLeft", "rectangle.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(11, "rectangle.nim");
	result = (*self).upperLeft;
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g, lowerRight_0oeftziOMeBmYGOVY3fE7g_2rectangle)(tyObject_Rectangle_Nmh3mhZ3Bmv7pIjRzEqLVg* self) {
	tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g result;
	nimfr_("lowerRight", "rectangle.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(12, "rectangle.nim");
	result = (*self).lowerRight;
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g, lowerLeft_0oeftziOMeBmYGOVY3fE7g_3rectangle)(tyObject_Rectangle_Nmh3mhZ3Bmv7pIjRzEqLVg* self) {
	tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g result;
	nimfr_("lowerLeft", "rectangle.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(14, "rectangle.nim");
	result.x = (*self).upperLeft.x;
	nimln_(15, "rectangle.nim");
	result.y = (*self).lowerRight.y;
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g, upperRight_0oeftziOMeBmYGOVY3fE7g_4rectangle)(tyObject_Rectangle_Nmh3mhZ3Bmv7pIjRzEqLVg* self) {
	tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g result;
	nimfr_("upperRight", "rectangle.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(17, "rectangle.nim");
	result.x = (*self).lowerRight.x;
	nimln_(18, "rectangle.nim");
	result.y = (*self).upperLeft.y;
	popFrame();
	return result;
}

static N_INLINE(NI, x_prTrI1MVo8MT9chBkL9c6JIArectangle)(tyObject_Rectangle_Nmh3mhZ3Bmv7pIjRzEqLVg* self) {
	NI result;
	nimfr_("x", "rectangle.nim");
	result = (NI)0;
	nimln_(20, "rectangle.nim");
	result = (*self).upperLeft.x;
	popFrame();
	return result;
}

static N_INLINE(NI, y_prTrI1MVo8MT9chBkL9c6JIA_2rectangle)(tyObject_Rectangle_Nmh3mhZ3Bmv7pIjRzEqLVg* self) {
	NI result;
	nimfr_("y", "rectangle.nim");
	result = (NI)0;
	nimln_(21, "rectangle.nim");
	result = (*self).upperLeft.y;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, width_prTrI1MVo8MT9chBkL9c6JIA_3rectangle)(tyObject_Rectangle_Nmh3mhZ3Bmv7pIjRzEqLVg* self) {
	NI result;
	NI TM_20UnZOr9bevAwgKUDj8kGFA_4;
	nimfr_("width", "rectangle.nim");
	result = (NI)0;
	nimln_(23, "rectangle.nim");
	TM_20UnZOr9bevAwgKUDj8kGFA_4 = subInt((*self).lowerRight.x, (*self).upperLeft.x);
	result = (NI)(TM_20UnZOr9bevAwgKUDj8kGFA_4);
	popFrame();
	return result;
}

static N_INLINE(NI, height_prTrI1MVo8MT9chBkL9c6JIA_4rectangle)(tyObject_Rectangle_Nmh3mhZ3Bmv7pIjRzEqLVg* self) {
	NI result;
	NI TM_20UnZOr9bevAwgKUDj8kGFA_5;
	nimfr_("height", "rectangle.nim");
	result = (NI)0;
	nimln_(25, "rectangle.nim");
	TM_20UnZOr9bevAwgKUDj8kGFA_5 = subInt((*self).lowerRight.y, (*self).upperLeft.y);
	result = (NI)(TM_20UnZOr9bevAwgKUDj8kGFA_5);
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	result = (NI)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, forEach_oCglDafOf4YskssJpz4WFA)(tyObject_Rectangle_Nmh3mhZ3Bmv7pIjRzEqLVg* self, tyProc_U9b2RsxBr7YW05GXUbwbFqw f) {
	NI width;
	NI height;
	NI length;
	NI TM_20UnZOr9bevAwgKUDj8kGFA_6;
	nimfr_("forEach", "rectangle.nim");
	nimln_(28, "rectangle.nim");
	width = width_prTrI1MVo8MT9chBkL9c6JIA_3rectangle(self);
	nimln_(29, "rectangle.nim");
	height = height_prTrI1MVo8MT9chBkL9c6JIA_4rectangle(self);
	nimln_(30, "rectangle.nim");
	TM_20UnZOr9bevAwgKUDj8kGFA_6 = mulInt(width, height);
	length = (NI)(TM_20UnZOr9bevAwgKUDj8kGFA_6);
	{
		NI i;
		NI colontmp_;
		NI TM_20UnZOr9bevAwgKUDj8kGFA_7;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(31, "rectangle.nim");
		TM_20UnZOr9bevAwgKUDj8kGFA_7 = subInt(length, ((NI) 1));
		colontmp_ = (NI)(TM_20UnZOr9bevAwgKUDj8kGFA_7);
		nimln_(2045, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI y;
				NI TM_20UnZOr9bevAwgKUDj8kGFA_8;
				NI x;
				NI TM_20UnZOr9bevAwgKUDj8kGFA_9;
				NI TM_20UnZOr9bevAwgKUDj8kGFA_11;
				if (!(res <= colontmp_)) goto LA3;
				nimln_(2047, "system.nim");
				i = res;
				nimln_(32, "rectangle.nim");
				TM_20UnZOr9bevAwgKUDj8kGFA_8 = divInt(i, width);
				y = (NI)(TM_20UnZOr9bevAwgKUDj8kGFA_8);
				nimln_(33, "rectangle.nim");
				TM_20UnZOr9bevAwgKUDj8kGFA_9 = modInt(i, width);
				x = (NI)(TM_20UnZOr9bevAwgKUDj8kGFA_9);
				nimln_(34, "rectangle.nim");
				f.ClE_0? f.ClP_0(x, y, f.ClE_0):((TM_20UnZOr9bevAwgKUDj8kGFA_10)(f.ClP_0))(x, y);
				nimln_(2048, "system.nim");
				TM_20UnZOr9bevAwgKUDj8kGFA_11 = addInt(res, ((NI) 1));
				res = (NI)(TM_20UnZOr9bevAwgKUDj8kGFA_11);
			} LA3: ;
		}
	}
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, smoke_rectangleInit000)(void) {
	nimfr_("rectangle", "rectangle.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, smoke_rectangleDatInit000)(void) {
}

