/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -I"C:\Program Files\nim\nim-0.18.0\lib" -o "C:\Users\Quinn Freedman\workspace\nim\smoke\src\nimcache\smoke_render.o" "C:\Users\Quinn Freedman\workspace\nim\smoke\src\nimcache\smoke_render.c" */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw;
typedef struct tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ;
typedef struct tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g;
typedef struct tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg;
typedef struct tyTuple_rTI1z5tLuTbP9b133u2ve6A tyTuple_rTI1z5tLuTbP9b133u2ve6A;
typedef struct tyObject_Matrix_5jfXleRjKMzj7p29cba2i9bg tyObject_Matrix_5jfXleRjKMzj7p29cba2i9bg;
typedef struct tySequence_6MHxSSkCYafnfGYzxyCqtA tySequence_6MHxSSkCYafnfGYzxyCqtA;
typedef struct tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg;
typedef struct tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA;
typedef struct tyObject_ItemSet_q6qi9bPVWXyspg9bTRkyuyXw tyObject_ItemSet_q6qi9bPVWXyspg9bTRkyuyXw;
typedef struct tyObject_ClothingHead_h3YfKnLVYVYocWj5dIBPGw tyObject_ClothingHead_h3YfKnLVYVYocWj5dIBPGw;
typedef struct tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_ClothingBody_jYCMVvD4caXGho8aDSyHJQ tyObject_ClothingBody_jYCMVvD4caXGho8aDSyHJQ;
typedef struct tyObject_ClothingFeet_UGmkgjwjxmZBaRBpyJpGvw tyObject_ClothingFeet_UGmkgjwjxmZBaRBpyJpGvw;
typedef struct tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA;
typedef struct tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ;
typedef struct tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw;
typedef struct tySequence_shxop0zPIs5Ec3k71aCLuQ tySequence_shxop0zPIs5Ec3k71aCLuQ;
struct tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ {
int Field0;
int Field1;
int Field2;
int Field3;
};
struct tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g {
NI x;
NI y;
};
typedef NI32 tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw;
typedef N_CDECL_PTR(tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw, tyProc_uEPg0xGcL9ao0XgF3q7VnpA) (tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* texture, tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ* srcrect, tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ* dstrect, double angle, tyTuple_rTI1z5tLuTbP9b133u2ve6A* center, int flip);
struct tyObject_Matrix_5jfXleRjKMzj7p29cba2i9bg {
NI width;
NI height;
tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g offset;
tySequence_6MHxSSkCYafnfGYzxyCqtA* data;
};
typedef NU8 tyEnum_TextureAlias_6sotYNRMaoTgzBzqkJyyLQ;
typedef tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* tyArray_3edo6skDm9cM0PXLYCHqS4g[3];
struct tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA {
NF x;
NF y;
};
typedef NU8 tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg;
typedef NU8 tyEnum_Race_wN6IdQU5M5xJLM35A76jlQ;
typedef NU8 tyEnum_Sex_fZXzEuE89cG49aK9cXfwfCxeQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg {
NimStringDesc* name;
};
struct tyObject_ClothingHead_h3YfKnLVYVYocWj5dIBPGw {
tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg stats;
};
struct tyObject_ClothingBody_jYCMVvD4caXGho8aDSyHJQ {
tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg stats;
};
struct tyObject_ClothingFeet_UGmkgjwjxmZBaRBpyJpGvw {
tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg stats;
};
struct tyObject_ItemSet_q6qi9bPVWXyspg9bTRkyuyXw {
tyObject_ClothingHead_h3YfKnLVYVYocWj5dIBPGw head;
tyObject_ClothingBody_jYCMVvD4caXGho8aDSyHJQ body;
tyObject_ClothingFeet_UGmkgjwjxmZBaRBpyJpGvw legs;
};
struct tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg {
tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g currentTile;
tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g nextTile;
tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA actualPos;
tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg facing;
NF speed;
tyEnum_Race_wN6IdQU5M5xJLM35A76jlQ race;
tyEnum_Sex_fZXzEuE89cG49aK9cXfwfCxeQ sex;
tyObject_ItemSet_q6qi9bPVWXyspg9bTRkyuyXw items;
tyEnum_TextureAlias_6sotYNRMaoTgzBzqkJyyLQ spritesheet;
};
typedef NIM_BOOL tyArray_k64wcrcoLEGgK5bVTvG2WA[6];
struct tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw {
NI width;
NI height;
tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g offset;
tySequence_shxop0zPIs5Ec3k71aCLuQ* data;
};
struct tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ {
tyObject_Matrix_5jfXleRjKMzj7p29cba2i9bg mapTextures;
tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw walls;
tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg playerCharacter;
};
struct tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA {
tyArray_k64wcrcoLEGgK5bVTvG2WA inputs;
tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer;
tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ gameState;
};
struct tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw {
char dummy;
};
struct tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg {
char dummy;
};
struct tyTuple_rTI1z5tLuTbP9b133u2ve6A {
int Field0;
int Field1;
};
struct tySequence_6MHxSSkCYafnfGYzxyCqtA {
  TGenericSeq Sup;
  tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ data[SEQ_DECL_SIZE];
};
struct tySequence_shxop0zPIs5Ec3k71aCLuQ {
  TGenericSeq Sup;
  NIM_BOOL data[SEQ_DECL_SIZE];
};
static N_INLINE(void, renderTile_6CJ7JYxCFonnknfbJUWsNwrender)(tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* texture, tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ srcRect, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g pos, tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g transform);
static N_INLINE(tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ, newSdlSquare_mKM48VTwEP7kEujb4tDg9aAutils)(NI x, NI y, NI w);
static N_INLINE(tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ, newSdlRect_pa4EWXFGguTRJoHOGgvabQutils)(NI x, NI y, NI w, NI h);
N_LIB_PRIVATE N_CDECL(tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ, rect_GH33Rh9bTnVBRLuu9bU7xoyA)(int x, int y, int w, int h);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, drawImage_xBsnA2Kafuz5HqH3exgc1Arender)(tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* texture, tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ* srcRect, tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ* destRect, tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g transform);
N_LIB_PRIVATE N_NIMCALL(void, renderMap_mSDA0S0vPkgYsFIROCc3Mw)(tyObject_Matrix_5jfXleRjKMzj7p29cba2i9bg* map, tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g transfrom);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NI, divInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g, v_g7Ok4O0iyLEmW9bny8ZknmA)(NI x, NI y);
static N_INLINE(tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ, X5BX5D__RO9bqf9bXJArfKnntsZlNbFQrender)(tyObject_Matrix_5jfXleRjKMzj7p29cba2i9bg* self, NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ, get_uvL9bK1KOZ240Zsp9cvalHnw)(tyObject_Matrix_5jfXleRjKMzj7p29cba2i9bg* self, NI x, NI y);
static N_INLINE(tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw*, getTexture_QAjyN0lMUqn9aw9bErnIVY4Qtextures)(tyEnum_TextureAlias_6sotYNRMaoTgzBzqkJyyLQ texture);
N_LIB_PRIVATE N_NIMCALL(void, renderCharacter_QOudD6LaUYNNzGHjMYt89bQ)(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg* character, tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g transfrom);
N_LIB_PRIVATE N_NIMCALL(tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ, getSrcRect_iww7nM41PPhFhiPsRXNe5A)(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg* self);
N_LIB_PRIVATE N_NIMCALL(tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ, getDestRect_iww7nM41PPhFhiPsRXNe5A_2)(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg* self);
N_LIB_PRIVATE N_NIMCALL(void, renderGameFrame_DNr2pOUK8Aw01XldiYBEiA)(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA** game);
N_NOINLINE(void, chckNil)(void* p);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyProc_uEPg0xGcL9ao0XgF3q7VnpA Dl_146995_;
extern tyArray_3edo6skDm9cM0PXLYCHqS4g texturStore_OAeI2tGiDQMmseHBRU5W9cA;

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ, newSdlRect_pa4EWXFGguTRJoHOGgvabQutils)(NI x, NI y, NI w, NI h) {
	tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ result;
	nimfr_("newSdlRect", "utils.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(4, "utils.nim");
	result = rect_GH33Rh9bTnVBRLuu9bU7xoyA(((int)chckRange(x, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(y, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(w, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(h, ((int) (-2147483647 -1)), ((int) 2147483647))));
	popFrame();
	return result;
}

static N_INLINE(tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ, newSdlSquare_mKM48VTwEP7kEujb4tDg9aAutils)(NI x, NI y, NI w) {
	tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ result;
	nimfr_("newSdlSquare", "utils.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(7, "utils.nim");
	result = newSdlRect_pa4EWXFGguTRJoHOGgvabQutils(x, y, w, w);
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, renderTile_6CJ7JYxCFonnknfbJUWsNwrender)(tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* texture, tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ srcRect, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g pos, tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g transform) {
	tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ drect;
	NI TM_UZPstdIgyxE9bQJbAjDif6g_2;
	NI TM_UZPstdIgyxE9bQJbAjDif6g_3;
	tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ srect;
	tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw _;
	nimfr_("renderTile", "render.nim");
	nimln_(20, "render.nim");
	nimln_(21, "render.nim");
	TM_UZPstdIgyxE9bQJbAjDif6g_2 = addInt(pos.x, transform.x);
	TM_UZPstdIgyxE9bQJbAjDif6g_3 = addInt(pos.y, transform.y);
	drect = newSdlSquare_mKM48VTwEP7kEujb4tDg9aAutils((NI)(TM_UZPstdIgyxE9bQJbAjDif6g_2), (NI)(TM_UZPstdIgyxE9bQJbAjDif6g_3), ((NI) 32));
	nimln_(23, "render.nim");
	srect = srcRect;
	nimln_(24, "render.nim");
	_ = Dl_146995_(renderer, texture, (&srect), (&drect), 0.0, NIM_NIL, ((int) 0));
	popFrame();
}

static N_INLINE(void, drawImage_xBsnA2Kafuz5HqH3exgc1Arender)(tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* texture, tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ* srcRect, tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ* destRect, tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g transform) {
	tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ drect;
	NI TM_UZPstdIgyxE9bQJbAjDif6g_4;
	NI TM_UZPstdIgyxE9bQJbAjDif6g_5;
	tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw _;
	nimfr_("drawImage", "render.nim");
	nimln_(28, "render.nim");
	nimln_(29, "render.nim");
	TM_UZPstdIgyxE9bQJbAjDif6g_4 = addInt(((NI) ((*destRect).Field0)), transform.x);
	nimln_(30, "render.nim");
	TM_UZPstdIgyxE9bQJbAjDif6g_5 = addInt(((NI) ((*destRect).Field1)), transform.y);
	drect = rect_GH33Rh9bTnVBRLuu9bU7xoyA(((int)chckRange((NI)(TM_UZPstdIgyxE9bQJbAjDif6g_4), ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange((NI)(TM_UZPstdIgyxE9bQJbAjDif6g_5), ((int) (-2147483647 -1)), ((int) 2147483647))), (*destRect).Field2, (*destRect).Field3);
	nimln_(34, "render.nim");
	_ = Dl_146995_(renderer, texture, srcRect, (&drect), 0.0, NIM_NIL, ((int) 0));
	popFrame();
}

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	result = (NI)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ, X5BX5D__RO9bqf9bXJArfKnntsZlNbFQrender)(tyObject_Matrix_5jfXleRjKMzj7p29cba2i9bg* self, NI x, NI y) {
	tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ result;
	nimfr_("[]", "matrix.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(48, "matrix.nim");
	result = get_uvL9bK1KOZ240Zsp9cvalHnw(self, x, y);
	popFrame();
	return result;
}

static N_INLINE(tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw*, getTexture_QAjyN0lMUqn9aw9bErnIVY4Qtextures)(tyEnum_TextureAlias_6sotYNRMaoTgzBzqkJyyLQ texture) {
	tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* result;
	nimfr_("getTexture", "textures.nim");
	result = (tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw*)0;
	nimln_(62, "textures.nim");
	result = texturStore_OAeI2tGiDQMmseHBRU5W9cA[(texture)- 0];
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, renderMap_mSDA0S0vPkgYsFIROCc3Mw)(tyObject_Matrix_5jfXleRjKMzj7p29cba2i9bg* map, tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g transfrom) {
	nimfr_("renderMap", "render.nim");
	{
		NI x;
		NI y;
		tyObject_Matrix_5jfXleRjKMzj7p29cba2i9bg colontmp_;
		NI width;
		NI height;
		x = (NI)0;
		y = (NI)0;
		memset((void*)(&colontmp_), 0, sizeof(colontmp_));
		nimln_(40, "render.nim");
		colontmp_.width = (*map).width;
		colontmp_.height = (*map).height;
		colontmp_.offset = (*map).offset;
		colontmp_.data = (*map).data;
		nimln_(78, "matrix.nim");
		width = colontmp_.width;
		nimln_(79, "matrix.nim");
		height = colontmp_.height;
		{
			NI i;
			NI colontmp__2;
			NI TM_UZPstdIgyxE9bQJbAjDif6g_6;
			NI i_2;
			i = (NI)0;
			colontmp__2 = (NI)0;
			nimln_(80, "matrix.nim");
			TM_UZPstdIgyxE9bQJbAjDif6g_6 = mulInt(width, height);
			colontmp__2 = (NI)(TM_UZPstdIgyxE9bQJbAjDif6g_6);
			nimln_(3519, "system.nim");
			i_2 = ((NI) 0);
			{
				nimln_(3520, "system.nim");
				while (1) {
					NI x_2;
					NI TM_UZPstdIgyxE9bQJbAjDif6g_7;
					NI TM_UZPstdIgyxE9bQJbAjDif6g_8;
					NI y_2;
					NI TM_UZPstdIgyxE9bQJbAjDif6g_9;
					NI TM_UZPstdIgyxE9bQJbAjDif6g_10;
					tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g pos;
					NI TM_UZPstdIgyxE9bQJbAjDif6g_11;
					NI TM_UZPstdIgyxE9bQJbAjDif6g_12;
					tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ srect;
					tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* T5_;
					NI TM_UZPstdIgyxE9bQJbAjDif6g_13;
					if (!(i_2 < colontmp__2)) goto LA4;
					nimln_(3521, "system.nim");
					i = i_2;
					nimln_(81, "matrix.nim");
					TM_UZPstdIgyxE9bQJbAjDif6g_7 = modInt(i, width);
					TM_UZPstdIgyxE9bQJbAjDif6g_8 = addInt((NI)(TM_UZPstdIgyxE9bQJbAjDif6g_7), colontmp_.offset.x);
					x_2 = (NI)(TM_UZPstdIgyxE9bQJbAjDif6g_8);
					nimln_(82, "matrix.nim");
					TM_UZPstdIgyxE9bQJbAjDif6g_9 = divInt(i, width);
					TM_UZPstdIgyxE9bQJbAjDif6g_10 = addInt((NI)(TM_UZPstdIgyxE9bQJbAjDif6g_9), colontmp_.offset.y);
					y_2 = (NI)(TM_UZPstdIgyxE9bQJbAjDif6g_10);
					nimln_(83, "matrix.nim");
					x = x_2;
					y = y_2;
					nimln_(41, "render.nim");
					TM_UZPstdIgyxE9bQJbAjDif6g_11 = mulInt(x, ((NI) 32));
					TM_UZPstdIgyxE9bQJbAjDif6g_12 = mulInt(y, ((NI) 32));
					pos = v_g7Ok4O0iyLEmW9bny8ZknmA((NI)(TM_UZPstdIgyxE9bQJbAjDif6g_11), (NI)(TM_UZPstdIgyxE9bQJbAjDif6g_12));
					nimln_(42, "render.nim");
					srect = X5BX5D__RO9bqf9bXJArfKnntsZlNbFQrender(map, x, y);
					nimln_(43, "render.nim");
					T5_ = (tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw*)0;
					T5_ = getTexture_QAjyN0lMUqn9aw9bErnIVY4Qtextures(((tyEnum_TextureAlias_6sotYNRMaoTgzBzqkJyyLQ) 0));
					renderTile_6CJ7JYxCFonnknfbJUWsNwrender(T5_, srect, pos, renderer, transfrom);
					nimln_(3522, "system.nim");
					TM_UZPstdIgyxE9bQJbAjDif6g_13 = addInt(i_2, ((NI) 1));
					i_2 = (NI)(TM_UZPstdIgyxE9bQJbAjDif6g_13);
				} LA4: ;
			}
		}
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, renderCharacter_QOudD6LaUYNNzGHjMYt89bQ)(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg* character, tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g transfrom) {
	tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ srect;
	tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ drect;
	tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* T1_;
	nimfr_("renderCharacter", "render.nim");
	nimln_(49, "render.nim");
	srect = getSrcRect_iww7nM41PPhFhiPsRXNe5A((&(*character)));
	nimln_(50, "render.nim");
	drect = getDestRect_iww7nM41PPhFhiPsRXNe5A_2((&(*character)));
	nimln_(51, "render.nim");
	T1_ = (tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw*)0;
	T1_ = getTexture_QAjyN0lMUqn9aw9bErnIVY4Qtextures((*character).spritesheet);
	drawImage_xBsnA2Kafuz5HqH3exgc1Arender(T1_, (&srect), (&drect), renderer, transfrom);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, renderGameFrame_DNr2pOUK8Aw01XldiYBEiA)(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA** game) {
	tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g transform;
	nimfr_("renderGameFrame", "render.nim");
	nimln_(56, "render.nim");
	chckNil((void*)(&transform));
	memset((void*)(&transform), 0, sizeof(transform));
	transform.x = ((NI) 0);
	transform.y = ((NI) 0);
	nimln_(57, "render.nim");
	renderMap_mSDA0S0vPkgYsFIROCc3Mw((&(*(*game)).gameState.mapTextures), (*(*game)).renderer, transform);
	nimln_(58, "render.nim");
	renderCharacter_QOudD6LaUYNNzGHjMYt89bQ((&(*(*game)).gameState.playerCharacter), (*(*game)).renderer, transform);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, smoke_renderInit000)(void) {
	nimfr_("render", "render.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, smoke_renderDatInit000)(void) {
}

