/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -I"C:\Program Files\nim\nim-0.18.0\lib" -o "C:\Users\Quinn Freedman\workspace\nim\smoke\src\nimcache\smoke_character.o" "C:\Users\Quinn Freedman\workspace\nim\smoke\src\nimcache\smoke_character.c" */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg;
typedef struct tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g;
typedef struct tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA;
typedef struct tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g {
NI x;
NI y;
};
struct tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA {
NF x;
NF y;
};
typedef NU8 tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg;
typedef NU8 tyEnum_Race_wN6IdQU5M5xJLM35A76jlQ;
typedef NU8 tyEnum_Sex_fZXzEuE89cG49aK9cXfwfCxeQ;
struct tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg {
tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g currentTile;
tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g nextTile;
tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA actualPos;
tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg facing;
NF speed;
tyEnum_Race_wN6IdQU5M5xJLM35A76jlQ race;
tyEnum_Sex_fZXzEuE89cG49aK9cXfwfCxeQ sex;
};
struct tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ {
int Field0;
int Field1;
int Field2;
int Field3;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_LIB_PRIVATE N_NIMCALL(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg, newCharacter_Ia3w0EG3EIpjyMYcAfcqRA)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g pos, NF speed, tyEnum_Race_wN6IdQU5M5xJLM35A76jlQ race, tyEnum_Sex_fZXzEuE89cG49aK9cXfwfCxeQ sex);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA, vecFloat_wLBMIso0HfVHu8Xdofrefw)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g v);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, move_vRBvJ39aGLz6uMrHDS0JOhw)(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg* self, tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg dir);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq__3sx5tMT4Qxpu49b019b2MQFA)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g self, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g other);
N_LIB_PRIVATE N_NIMCALL(void, pluseq__nt8lzfAY8lk9aeXOHciJ8wQ)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g* self, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g other);
N_LIB_PRIVATE N_NIMCALL(void, update_pBfJunJAWPEnvkt2lnqkcA)(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg* self, NF dt);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA, minus__HfcuY0Uh67I09aLMQeXgCMQ_2)(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA self, tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA other);
static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils)(NF* x, NF y);
static N_INLINE(NI, sgn_R8sAE9aamvx9b6pyhd4pH4GAcharacter)(NF x);
static N_INLINE(NIM_BOOL, isMoving_2orV7oZYyKqlkTtJjSFrBgcharacter)(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg* self);
static N_INLINE(NF, animationTimer_p4f2Wbmj53U17sklrjoDkgcharacter)(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg* self);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g, minus__tYFBZAVkxpPzZkVM8ktKlQ_2)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g self, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g other);
N_LIB_PRIVATE N_NIMCALL(tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ, getSrcRect_iww7nM41PPhFhiPsRXNe5A)(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg* self);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ, newSdlSquare_mKM48VTwEP7kEujb4tDg9aAutils)(NI x, NI y, NI w);
static N_INLINE(tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ, newSdlRect_pa4EWXFGguTRJoHOGgvabQutils)(NI x, NI y, NI w, NI h);
N_LIB_PRIVATE N_CDECL(tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ, rect_GH33Rh9bTnVBRLuu9bU7xoyA)(int x, int y, int w, int h);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ, getDestRect_iww7nM41PPhFhiPsRXNe5A_2)(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg* self);
N_LIB_PRIVATE N_NIMCALL(NF, round_FL9bhksfuQsfLDCxRHuknsg)(NF x, NI places);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_z7sEl7rGLIEtgyeCSL9aOwg_;
extern TNimType NTI_7SQP9azfryP3zjoOAafzI6g_;
extern TNimType NTI_St31Lu7mm4aIQTpxOCjvHA_;
extern TNimType NTI_p7h0usAc9c3d7sTkU0MWLNg_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
TNimType NTI_wN6IdQU5M5xJLM35A76jlQ_;
TNimType NTI_fZXzEuE89cG49aK9cXfwfCxeQ_;
NIM_CONST tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g TM_PwTdfkrY8LpxXUaQ9btKuRA_2 = {((NI) 0), ((NI) -1)};
NIM_CONST tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g TM_PwTdfkrY8LpxXUaQ9btKuRA_3 = {((NI) 0), ((NI) 1)};
NIM_CONST tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g TM_PwTdfkrY8LpxXUaQ9btKuRA_4 = {((NI) -1), ((NI) 0)};
NIM_CONST tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g TM_PwTdfkrY8LpxXUaQ9btKuRA_5 = {((NI) 1), ((NI) 0)};

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg, newCharacter_Ia3w0EG3EIpjyMYcAfcqRA)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g pos, NF speed, tyEnum_Race_wN6IdQU5M5xJLM35A76jlQ race, tyEnum_Sex_fZXzEuE89cG49aK9cXfwfCxeQ sex) {
	tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg result;
	nimfr_("newCharacter", "character.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(26, "character.nim");
	result.currentTile = pos;
	nimln_(27, "character.nim");
	result.nextTile = pos;
	nimln_(28, "character.nim");
	result.actualPos = vecFloat_wLBMIso0HfVHu8Xdofrefw(pos);
	nimln_(29, "character.nim");
	result.facing = ((tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg) 1);
	nimln_(30, "character.nim");
	result.speed = speed;
	nimln_(31, "character.nim");
	result.race = race;
	nimln_(32, "character.nim");
	result.sex = sex;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, move_vRBvJ39aGLz6uMrHDS0JOhw)(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg* self, tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg dir) {
	nimfr_("move", "character.nim");
{	nimln_(36, "character.nim");
	{
		NIM_BOOL T3_;
		nimln_(398, "system.nim");
		nimln_(36, "character.nim");
		T3_ = (NIM_BOOL)0;
		T3_ = eqeq__3sx5tMT4Qxpu49b019b2MQFA((*self).currentTile, (*self).nextTile);
		if (!!(T3_)) goto LA4_;
		nimln_(37, "character.nim");
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(39, "character.nim");
	(*self).facing = dir;
	nimln_(41, "character.nim");
	switch (dir) {
	case ((tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg) 0):
	{
		nimln_(43, "character.nim");
		pluseq__nt8lzfAY8lk9aeXOHciJ8wQ((&(*self).nextTile), TM_PwTdfkrY8LpxXUaQ9btKuRA_2);
	}
	break;
	case ((tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg) 1):
	{
		nimln_(45, "character.nim");
		pluseq__nt8lzfAY8lk9aeXOHciJ8wQ((&(*self).nextTile), TM_PwTdfkrY8LpxXUaQ9btKuRA_3);
	}
	break;
	case ((tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg) 2):
	{
		nimln_(47, "character.nim");
		pluseq__nt8lzfAY8lk9aeXOHciJ8wQ((&(*self).nextTile), TM_PwTdfkrY8LpxXUaQ9btKuRA_4);
	}
	break;
	case ((tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg) 3):
	{
		nimln_(49, "character.nim");
		pluseq__nt8lzfAY8lk9aeXOHciJ8wQ((&(*self).nextTile), TM_PwTdfkrY8LpxXUaQ9btKuRA_5);
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
}

static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils)(NF* x, NF y) {
	nimfr_("+=", "system.nim");
	nimln_(3700, "system.nim");
	(*x) = ((NF)((*x)) + (NF)(y));
	popFrame();
}

static N_INLINE(NI, sgn_R8sAE9aamvx9b6pyhd4pH4GAcharacter)(NF x) {
	NI result;
	result = (NI)0;
	result = (NI)((0.0 < x) - (x < 0.0));
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, update_pBfJunJAWPEnvkt2lnqkcA)(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg* self, NF dt) {
	tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA dif;
	tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA T1_;
	NF moveAmount;
	nimfr_("update", "character.nim");
	nimln_(54, "character.nim");
	T1_ = vecFloat_wLBMIso0HfVHu8Xdofrefw((*self).nextTile);
	dif = minus__HfcuY0Uh67I09aLMQeXgCMQ_2(T1_, (*self).actualPos);
	nimln_(56, "character.nim");
	moveAmount = ((NF)((*self).speed) * (NF)(dt));
	nimln_(58, "character.nim");
	{
		if (!((dif.x < 0? -(dif.x) : (dif.x)) < moveAmount)) goto LA4_;
		nimln_(59, "character.nim");
		(*self).actualPos.x = ((NF) ((*self).nextTile.x));
	}
	goto LA2_;
	LA4_: ;
	{
		NI T7_;
		nimln_(61, "character.nim");
		T7_ = (NI)0;
		T7_ = sgn_R8sAE9aamvx9b6pyhd4pH4GAcharacter(dif.x);
		pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&(*self).actualPos.x), ((NF)(((NF) (T7_))) * (NF)(moveAmount)));
	}
	LA2_: ;
	nimln_(63, "character.nim");
	{
		if (!((dif.y < 0? -(dif.y) : (dif.y)) < moveAmount)) goto LA10_;
		nimln_(64, "character.nim");
		(*self).actualPos.y = ((NF) ((*self).nextTile.y));
	}
	goto LA8_;
	LA10_: ;
	{
		NI T13_;
		nimln_(66, "character.nim");
		T13_ = (NI)0;
		T13_ = sgn_R8sAE9aamvx9b6pyhd4pH4GAcharacter(dif.y);
		pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&(*self).actualPos.y), ((NF)(((NF) (T13_))) * (NF)(moveAmount)));
	}
	LA8_: ;
	nimln_(68, "character.nim");
	{
		NIM_BOOL T16_;
		T16_ = (NIM_BOOL)0;
		T16_ = ((dif.x < 0? -(dif.x) : (dif.x)) < moveAmount);
		if (!(T16_)) goto LA17_;
		T16_ = ((dif.y < 0? -(dif.y) : (dif.y)) < moveAmount);
		LA17_: ;
		if (!T16_) goto LA18_;
		nimln_(69, "character.nim");
		(*self).currentTile = (*self).nextTile;
	}
	LA18_: ;
	popFrame();
}

static N_INLINE(NIM_BOOL, isMoving_2orV7oZYyKqlkTtJjSFrBgcharacter)(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg* self) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("isMoving", "character.nim");
	result = (NIM_BOOL)0;
	nimln_(73, "character.nim");
	nimln_(398, "system.nim");
	nimln_(73, "character.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = eqeq__3sx5tMT4Qxpu49b019b2MQFA((*self).currentTile, (*self).nextTile);
	result = !(T1_);
	popFrame();
	return result;
}

static N_INLINE(NF, animationTimer_p4f2Wbmj53U17sklrjoDkgcharacter)(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg* self) {
	NF result;
	tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA distanceToMove;
	tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g T1_;
	tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA distanceMoved;
	tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA T2_;
	nimfr_("animationTimer", "character.nim");
	result = (NF)0;
	nimln_(77, "character.nim");
	T1_ = minus__tYFBZAVkxpPzZkVM8ktKlQ_2((*self).nextTile, (*self).currentTile);
	distanceToMove = vecFloat_wLBMIso0HfVHu8Xdofrefw(T1_);
	nimln_(78, "character.nim");
	T2_ = vecFloat_wLBMIso0HfVHu8Xdofrefw((*self).nextTile);
	distanceMoved = minus__HfcuY0Uh67I09aLMQeXgCMQ_2(T2_, (*self).actualPos);
	nimln_(80, "character.nim");
	{
		nimln_(398, "system.nim");
		nimln_(80, "character.nim");
		if (!!((distanceToMove.x == 0.0))) goto LA5_;
		nimln_(81, "character.nim");
		result = ((NF)(distanceMoved.x) / (NF)(distanceToMove.x));
	}
	goto LA3_;
	LA5_: ;
	{
		nimln_(398, "system.nim");
		nimln_(82, "character.nim");
		if (!!((distanceToMove.y == 0.0))) goto LA8_;
		nimln_(83, "character.nim");
		result = ((NF)(distanceMoved.y) / (NF)(distanceToMove.y));
	}
	goto LA3_;
	LA8_: ;
	{
		result = 0.0;
	}
	LA3_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	result = (NI)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ, newSdlRect_pa4EWXFGguTRJoHOGgvabQutils)(NI x, NI y, NI w, NI h) {
	tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ result;
	nimfr_("newSdlRect", "utils.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(4, "utils.nim");
	result = rect_GH33Rh9bTnVBRLuu9bU7xoyA(((int)chckRange(x, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(y, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(w, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(h, ((int) (-2147483647 -1)), ((int) 2147483647))));
	popFrame();
	return result;
}

static N_INLINE(tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ, newSdlSquare_mKM48VTwEP7kEujb4tDg9aAutils)(NI x, NI y, NI w) {
	tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ result;
	nimfr_("newSdlSquare", "utils.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(7, "utils.nim");
	result = newSdlRect_pa4EWXFGguTRJoHOGgvabQutils(x, y, w, w);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ, getSrcRect_iww7nM41PPhFhiPsRXNe5A)(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg* self) {
	tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ result;
	NI row;
	NI frame;
	NI TM_PwTdfkrY8LpxXUaQ9btKuRA_7;
	NI TM_PwTdfkrY8LpxXUaQ9btKuRA_8;
	nimfr_("getSrcRect", "character.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(88, "character.nim");
	nimln_(89, "character.nim");
	switch ((*self).facing) {
	case ((tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg) 1):
	{
		row = ((NI) 0);
	}
	break;
	case ((tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg) 3):
	{
		row = ((NI) 1);
	}
	break;
	case ((tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg) 2):
	{
		row = ((NI) 2);
	}
	break;
	case ((tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg) 0):
	{
		row = ((NI) 3);
	}
	break;
	}
	nimln_(95, "character.nim");
	nimln_(96, "character.nim");
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = isMoving_2orV7oZYyKqlkTtJjSFrBgcharacter(self);
		if (!!(T7_)) goto LA8_;
		frame = ((NI) 0);
	}
	goto LA5_;
	LA8_: ;
	{
		NF tilesPerSecond;
		NF secondsPerTile;
		NF T11_;
		NI TM_PwTdfkrY8LpxXUaQ9btKuRA_6;
		nimln_(99, "character.nim");
		tilesPerSecond = (*self).speed;
		nimln_(100, "character.nim");
		secondsPerTile = ((NF)(1.0000000000000000e+000) / (NF)(tilesPerSecond));
		nimln_(101, "character.nim");
		T11_ = (NF)0;
		T11_ = animationTimer_p4f2Wbmj53U17sklrjoDkgcharacter(self);
		TM_PwTdfkrY8LpxXUaQ9btKuRA_6 = modInt(((NI) (((NF)(((NF)(T11_) / (NF)(secondsPerTile))) * (NF)(7.0000000000000000e+000)))), ((NI) 7));
		frame = (NI)(TM_PwTdfkrY8LpxXUaQ9btKuRA_6);
	}
	LA5_: ;
	nimln_(103, "character.nim");
	TM_PwTdfkrY8LpxXUaQ9btKuRA_7 = mulInt(frame, ((NI) 32));
	TM_PwTdfkrY8LpxXUaQ9btKuRA_8 = mulInt(row, ((NI) 32));
	result = newSdlSquare_mKM48VTwEP7kEujb4tDg9aAutils((NI)(TM_PwTdfkrY8LpxXUaQ9btKuRA_7), (NI)(TM_PwTdfkrY8LpxXUaQ9btKuRA_8), ((NI) 32));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ, getDestRect_iww7nM41PPhFhiPsRXNe5A_2)(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg* self) {
	tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ result;
	NF T1_;
	NF T2_;
	nimfr_("getDestRect", "character.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(107, "character.nim");
	T1_ = (NF)0;
	T1_ = round_FL9bhksfuQsfLDCxRHuknsg(((NF)((*self).actualPos.x) * (NF)(3.2000000000000000e+001)), ((NI) 0));
	nimln_(108, "character.nim");
	T2_ = (NF)0;
	T2_ = round_FL9bhksfuQsfLDCxRHuknsg(((NF)((*self).actualPos.y) * (NF)(3.2000000000000000e+001)), ((NI) 0));
	result = newSdlSquare_mKM48VTwEP7kEujb4tDg9aAutils(((NI) (T1_)), ((NI) (T2_)), ((NI) 32));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, smoke_characterInit000)(void) {
	nimfr_("character", "character.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, smoke_characterDatInit000)(void) {
static TNimNode* TM_PwTdfkrY8LpxXUaQ9btKuRA_9[7];
static TNimNode* TM_PwTdfkrY8LpxXUaQ9btKuRA_10[1];
NI TM_PwTdfkrY8LpxXUaQ9btKuRA_12;
static char* NIM_CONST TM_PwTdfkrY8LpxXUaQ9btKuRA_11[1] = {
"human"};
static TNimNode* TM_PwTdfkrY8LpxXUaQ9btKuRA_13[2];
NI TM_PwTdfkrY8LpxXUaQ9btKuRA_15;
static char* NIM_CONST TM_PwTdfkrY8LpxXUaQ9btKuRA_14[2] = {
"male", 
"female"};
static TNimNode TM_PwTdfkrY8LpxXUaQ9btKuRA_0[13];
NTI_z7sEl7rGLIEtgyeCSL9aOwg_.size = sizeof(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg);
NTI_z7sEl7rGLIEtgyeCSL9aOwg_.kind = 18;
NTI_z7sEl7rGLIEtgyeCSL9aOwg_.base = 0;
NTI_z7sEl7rGLIEtgyeCSL9aOwg_.flags = 3;
TM_PwTdfkrY8LpxXUaQ9btKuRA_9[0] = &TM_PwTdfkrY8LpxXUaQ9btKuRA_0[1];
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[1].kind = 1;
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[1].offset = offsetof(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg, currentTile);
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[1].typ = (&NTI_7SQP9azfryP3zjoOAafzI6g_);
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[1].name = "currentTile";
TM_PwTdfkrY8LpxXUaQ9btKuRA_9[1] = &TM_PwTdfkrY8LpxXUaQ9btKuRA_0[2];
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[2].kind = 1;
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[2].offset = offsetof(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg, nextTile);
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[2].typ = (&NTI_7SQP9azfryP3zjoOAafzI6g_);
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[2].name = "nextTile";
TM_PwTdfkrY8LpxXUaQ9btKuRA_9[2] = &TM_PwTdfkrY8LpxXUaQ9btKuRA_0[3];
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[3].kind = 1;
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[3].offset = offsetof(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg, actualPos);
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[3].typ = (&NTI_St31Lu7mm4aIQTpxOCjvHA_);
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[3].name = "actualPos";
TM_PwTdfkrY8LpxXUaQ9btKuRA_9[3] = &TM_PwTdfkrY8LpxXUaQ9btKuRA_0[4];
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[4].kind = 1;
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[4].offset = offsetof(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg, facing);
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[4].typ = (&NTI_p7h0usAc9c3d7sTkU0MWLNg_);
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[4].name = "facing";
TM_PwTdfkrY8LpxXUaQ9btKuRA_9[4] = &TM_PwTdfkrY8LpxXUaQ9btKuRA_0[5];
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[5].kind = 1;
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[5].offset = offsetof(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg, speed);
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[5].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[5].name = "speed";
TM_PwTdfkrY8LpxXUaQ9btKuRA_9[5] = &TM_PwTdfkrY8LpxXUaQ9btKuRA_0[6];
NTI_wN6IdQU5M5xJLM35A76jlQ_.size = sizeof(tyEnum_Race_wN6IdQU5M5xJLM35A76jlQ);
NTI_wN6IdQU5M5xJLM35A76jlQ_.kind = 14;
NTI_wN6IdQU5M5xJLM35A76jlQ_.base = 0;
NTI_wN6IdQU5M5xJLM35A76jlQ_.flags = 3;
for (TM_PwTdfkrY8LpxXUaQ9btKuRA_12 = 0; TM_PwTdfkrY8LpxXUaQ9btKuRA_12 < 1; TM_PwTdfkrY8LpxXUaQ9btKuRA_12++) {
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[TM_PwTdfkrY8LpxXUaQ9btKuRA_12+7].kind = 1;
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[TM_PwTdfkrY8LpxXUaQ9btKuRA_12+7].offset = TM_PwTdfkrY8LpxXUaQ9btKuRA_12;
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[TM_PwTdfkrY8LpxXUaQ9btKuRA_12+7].name = TM_PwTdfkrY8LpxXUaQ9btKuRA_11[TM_PwTdfkrY8LpxXUaQ9btKuRA_12];
TM_PwTdfkrY8LpxXUaQ9btKuRA_10[TM_PwTdfkrY8LpxXUaQ9btKuRA_12] = &TM_PwTdfkrY8LpxXUaQ9btKuRA_0[TM_PwTdfkrY8LpxXUaQ9btKuRA_12+7];
}
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[8].len = 1; TM_PwTdfkrY8LpxXUaQ9btKuRA_0[8].kind = 2; TM_PwTdfkrY8LpxXUaQ9btKuRA_0[8].sons = &TM_PwTdfkrY8LpxXUaQ9btKuRA_10[0];
NTI_wN6IdQU5M5xJLM35A76jlQ_.node = &TM_PwTdfkrY8LpxXUaQ9btKuRA_0[8];
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[6].kind = 1;
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[6].offset = offsetof(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg, race);
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[6].typ = (&NTI_wN6IdQU5M5xJLM35A76jlQ_);
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[6].name = "race";
TM_PwTdfkrY8LpxXUaQ9btKuRA_9[6] = &TM_PwTdfkrY8LpxXUaQ9btKuRA_0[9];
NTI_fZXzEuE89cG49aK9cXfwfCxeQ_.size = sizeof(tyEnum_Sex_fZXzEuE89cG49aK9cXfwfCxeQ);
NTI_fZXzEuE89cG49aK9cXfwfCxeQ_.kind = 14;
NTI_fZXzEuE89cG49aK9cXfwfCxeQ_.base = 0;
NTI_fZXzEuE89cG49aK9cXfwfCxeQ_.flags = 3;
for (TM_PwTdfkrY8LpxXUaQ9btKuRA_15 = 0; TM_PwTdfkrY8LpxXUaQ9btKuRA_15 < 2; TM_PwTdfkrY8LpxXUaQ9btKuRA_15++) {
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[TM_PwTdfkrY8LpxXUaQ9btKuRA_15+10].kind = 1;
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[TM_PwTdfkrY8LpxXUaQ9btKuRA_15+10].offset = TM_PwTdfkrY8LpxXUaQ9btKuRA_15;
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[TM_PwTdfkrY8LpxXUaQ9btKuRA_15+10].name = TM_PwTdfkrY8LpxXUaQ9btKuRA_14[TM_PwTdfkrY8LpxXUaQ9btKuRA_15];
TM_PwTdfkrY8LpxXUaQ9btKuRA_13[TM_PwTdfkrY8LpxXUaQ9btKuRA_15] = &TM_PwTdfkrY8LpxXUaQ9btKuRA_0[TM_PwTdfkrY8LpxXUaQ9btKuRA_15+10];
}
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[12].len = 2; TM_PwTdfkrY8LpxXUaQ9btKuRA_0[12].kind = 2; TM_PwTdfkrY8LpxXUaQ9btKuRA_0[12].sons = &TM_PwTdfkrY8LpxXUaQ9btKuRA_13[0];
NTI_fZXzEuE89cG49aK9cXfwfCxeQ_.node = &TM_PwTdfkrY8LpxXUaQ9btKuRA_0[12];
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[9].kind = 1;
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[9].offset = offsetof(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg, sex);
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[9].typ = (&NTI_fZXzEuE89cG49aK9cXfwfCxeQ_);
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[9].name = "sex";
TM_PwTdfkrY8LpxXUaQ9btKuRA_0[0].len = 7; TM_PwTdfkrY8LpxXUaQ9btKuRA_0[0].kind = 2; TM_PwTdfkrY8LpxXUaQ9btKuRA_0[0].sons = &TM_PwTdfkrY8LpxXUaQ9btKuRA_9[0];
NTI_z7sEl7rGLIEtgyeCSL9aOwg_.node = &TM_PwTdfkrY8LpxXUaQ9btKuRA_0[0];
}

