/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -I"C:\Program Files\nim\nim-0.18.0\lib" -o "C:\Users\Quinn Freedman\workspace\nim\smoke\src\nimcache\smoke_shadowcasting.o" "C:\Users\Quinn Freedman\workspace\nim\smoke\src\nimcache\smoke_shadowcasting.c" */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_I8SFWagEVlP5ALbfNGFGHg tyTuple_I8SFWagEVlP5ALbfNGFGHg;
typedef struct tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g;
typedef struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw;
typedef struct tySequence_shxop0zPIs5Ec3k71aCLuQ tySequence_shxop0zPIs5Ec3k71aCLuQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g {
NI x;
NI y;
};
struct tyTuple_I8SFWagEVlP5ALbfNGFGHg {
tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g Field0;
tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g Field1;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA {
  Exception Sup;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw {
NI width;
NI height;
tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g offset;
tySequence_shxop0zPIs5Ec3k71aCLuQ* data;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
struct tySequence_shxop0zPIs5Ec3k71aCLuQ {
  TGenericSeq Sup;
  NIM_BOOL data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(tyTuple_I8SFWagEVlP5ALbfNGFGHg, getOctant_Ls6FZas9bfAld2TkySjUC3g)(NI octant);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_LIB_PRIVATE N_NIMCALL(void, castOctant_m9aAGV5kdbzAn9ca9aQ8s3ePw)(NI octant, tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw* mask, tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw* walls, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g pos, NIM_BOOL inShadow);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g, plus__tYFBZAVkxpPzZkVM8ktKlQ)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g self, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g other);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_Hvqkdr9bF9az9aNEuE3gnxkyw)(tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw* self, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g vec);
static N_INLINE(void, X5BX5Deq__e9cvPO0mb4yr9aEJhgB6aRDQshadowcasting)(tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw* self, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g pos, NIM_BOOL value);
N_LIB_PRIVATE N_NIMCALL(void, set_dwKTQMqun8vrCrUIi6jcSg)(tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw* self, NI x, NI y, NIM_BOOL value);
static N_INLINE(NIM_BOOL, X5BX5D__0rBDPPdWWFDJijpMUm66Owshadowcasting)(tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw* self, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g pos);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, get_fj0Ppa0kNA1RuTZA6XWnMQ)(tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw* self, NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(void, shadowCast_3oBR9b4zVFsPhw2mvqbsMnw)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g heroPos, tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw* mask, tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw* walls);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
extern TNimType NTI_yCEN9anxCD6mzBxGjuaRBdg_;
extern TNimType NTI_Gi06FkNeykJn7mrqRZYrkA_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_shxop0zPIs5Ec3k71aCLuQ_;
NIM_CONST tyTuple_I8SFWagEVlP5ALbfNGFGHg TM_XK56NhFOhNnnHqqeg9a8zTg_2 = {{((NI) 0), ((NI) -1)},
{((NI) 1), ((NI) -1)}}
;
NIM_CONST tyTuple_I8SFWagEVlP5ALbfNGFGHg TM_XK56NhFOhNnnHqqeg9a8zTg_3 = {{((NI) 1), ((NI) -1)},
{((NI) 1), ((NI) 0)}}
;
NIM_CONST tyTuple_I8SFWagEVlP5ALbfNGFGHg TM_XK56NhFOhNnnHqqeg9a8zTg_4 = {{((NI) 1), ((NI) 0)},
{((NI) 1), ((NI) 1)}}
;
NIM_CONST tyTuple_I8SFWagEVlP5ALbfNGFGHg TM_XK56NhFOhNnnHqqeg9a8zTg_5 = {{((NI) 1), ((NI) 1)},
{((NI) 0), ((NI) 1)}}
;
NIM_CONST tyTuple_I8SFWagEVlP5ALbfNGFGHg TM_XK56NhFOhNnnHqqeg9a8zTg_6 = {{((NI) 0), ((NI) 1)},
{((NI) -1), ((NI) 1)}}
;
NIM_CONST tyTuple_I8SFWagEVlP5ALbfNGFGHg TM_XK56NhFOhNnnHqqeg9a8zTg_7 = {{((NI) -1), ((NI) 1)},
{((NI) -1), ((NI) 0)}}
;
NIM_CONST tyTuple_I8SFWagEVlP5ALbfNGFGHg TM_XK56NhFOhNnnHqqeg9a8zTg_8 = {{((NI) -1), ((NI) 0)},
{((NI) -1), ((NI) -1)}}
;
NIM_CONST tyTuple_I8SFWagEVlP5ALbfNGFGHg TM_XK56NhFOhNnnHqqeg9a8zTg_9 = {{((NI) -1), ((NI) -1)},
{((NI) 0), ((NI) -1)}}
;
STRING_LITERAL(TM_XK56NhFOhNnnHqqeg9a8zTg_10, "octant > 7", 10);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_I8SFWagEVlP5ALbfNGFGHg, getOctant_Ls6FZas9bfAld2TkySjUC3g)(NI octant) {
	tyTuple_I8SFWagEVlP5ALbfNGFGHg result;
	nimfr_("getOctant", "shadowcasting.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(6, "shadowcasting.nim");
	switch (octant) {
	case ((NI) 0):
	{
		result = TM_XK56NhFOhNnnHqqeg9a8zTg_2;
	}
	break;
	case ((NI) 1):
	{
		result = TM_XK56NhFOhNnnHqqeg9a8zTg_3;
	}
	break;
	case ((NI) 2):
	{
		result = TM_XK56NhFOhNnnHqqeg9a8zTg_4;
	}
	break;
	case ((NI) 3):
	{
		result = TM_XK56NhFOhNnnHqqeg9a8zTg_5;
	}
	break;
	case ((NI) 4):
	{
		result = TM_XK56NhFOhNnnHqqeg9a8zTg_6;
	}
	break;
	case ((NI) 5):
	{
		result = TM_XK56NhFOhNnnHqqeg9a8zTg_7;
	}
	break;
	case ((NI) 6):
	{
		result = TM_XK56NhFOhNnnHqqeg9a8zTg_8;
	}
	break;
	case ((NI) 7):
	{
		result = TM_XK56NhFOhNnnHqqeg9a8zTg_9;
	}
	break;
	default:
	{
		tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e;
		NimStringDesc* T10_;
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
		nimln_(2811, "system.nim");
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
		(*e).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
		nimln_(15, "shadowcasting.nim");
		T10_ = (NimStringDesc*)0;
		T10_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_XK56NhFOhNnnHqqeg9a8zTg_10));
		if (T10_) nimGCunrefNoCycle(T10_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(15, "shadowcasting.nim");
		raiseException((Exception*)e, "ValueError");
	}
	break;
	}
	popFrame();
	return result;
}

static N_INLINE(void, X5BX5Deq__e9cvPO0mb4yr9aEJhgB6aRDQshadowcasting)(tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw* self, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g pos, NIM_BOOL value) {
	nimfr_("[]=", "matrix.nim");
	nimln_(65, "matrix.nim");
	set_dwKTQMqun8vrCrUIi6jcSg(self, pos.x, pos.y, value);
	popFrame();
}

static N_INLINE(NIM_BOOL, X5BX5D__0rBDPPdWWFDJijpMUm66Owshadowcasting)(tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw* self, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g pos) {
	NIM_BOOL result;
	tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw mutSelf;
	nimfr_("[]", "matrix.nim");
	result = (NIM_BOOL)0;
	nimln_(58, "matrix.nim");
	memset((void*)(&mutSelf), 0, sizeof(mutSelf));
	mutSelf.width = (*self).width;
	mutSelf.height = (*self).height;
	mutSelf.offset = (*self).offset;
	genericSeqAssign((&mutSelf.data), (*self).data, (&NTI_shxop0zPIs5Ec3k71aCLuQ_));
	nimln_(59, "matrix.nim");
	result = get_fj0Ppa0kNA1RuTZA6XWnMQ((&mutSelf), pos.x, pos.y);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, castOctant_m9aAGV5kdbzAn9ca9aQ8s3ePw)(NI octant, tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw* mask, tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw* walls, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g pos, NIM_BOOL inShadow) {
	tyTuple_I8SFWagEVlP5ALbfNGFGHg octantVecs;
	tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g newPos;
	tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g newPos_2;
	nimfr_("castOctant", "shadowcasting.nim");
	nimln_(22, "shadowcasting.nim");
	octantVecs = getOctant_Ls6FZas9bfAld2TkySjUC3g(octant);
	nimln_(24, "shadowcasting.nim");
	newPos = plus__tYFBZAVkxpPzZkVM8ktKlQ(pos, octantVecs.Field0);
	nimln_(25, "shadowcasting.nim");
	{
		NIM_BOOL T3_;
		NIM_BOOL T10_;
		T3_ = (NIM_BOOL)0;
		T3_ = contains_Hvqkdr9bF9az9aNEuE3gnxkyw(mask, newPos);
		if (!T3_) goto LA4_;
		nimln_(26, "shadowcasting.nim");
		{
			if (!inShadow) goto LA8_;
			nimln_(27, "shadowcasting.nim");
			X5BX5Deq__e9cvPO0mb4yr9aEJhgB6aRDQshadowcasting(mask, newPos, NIM_TRUE);
		}
		LA8_: ;
		nimln_(29, "shadowcasting.nim");
		T10_ = (NIM_BOOL)0;
		T10_ = inShadow;
		if (T10_) goto LA11_;
		T10_ = X5BX5D__0rBDPPdWWFDJijpMUm66Owshadowcasting(walls, newPos);
		LA11_: ;
		castOctant_m9aAGV5kdbzAn9ca9aQ8s3ePw(octant, mask, walls, newPos, T10_);
	}
	LA4_: ;
	nimln_(24, "shadowcasting.nim");
	newPos_2 = plus__tYFBZAVkxpPzZkVM8ktKlQ(pos, octantVecs.Field1);
	nimln_(25, "shadowcasting.nim");
	{
		NIM_BOOL T14_;
		NIM_BOOL T21_;
		T14_ = (NIM_BOOL)0;
		T14_ = contains_Hvqkdr9bF9az9aNEuE3gnxkyw(mask, newPos_2);
		if (!T14_) goto LA15_;
		nimln_(26, "shadowcasting.nim");
		{
			if (!inShadow) goto LA19_;
			nimln_(27, "shadowcasting.nim");
			X5BX5Deq__e9cvPO0mb4yr9aEJhgB6aRDQshadowcasting(mask, newPos_2, NIM_TRUE);
		}
		LA19_: ;
		nimln_(29, "shadowcasting.nim");
		T21_ = (NIM_BOOL)0;
		T21_ = inShadow;
		if (T21_) goto LA22_;
		T21_ = X5BX5D__0rBDPPdWWFDJijpMUm66Owshadowcasting(walls, newPos_2);
		LA22_: ;
		castOctant_m9aAGV5kdbzAn9ca9aQ8s3ePw(octant, mask, walls, newPos_2, T21_);
	}
	LA15_: ;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, shadowCast_3oBR9b4zVFsPhw2mvqbsMnw)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g heroPos, tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw* mask, tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw* walls) {
	nimfr_("shadowCast", "shadowcasting.nim");
	nimln_(32, "shadowcasting.nim");
	X5BX5Deq__e9cvPO0mb4yr9aEJhgB6aRDQshadowcasting(mask, heroPos, NIM_FALSE);
	{
		NI i;
		NI i_2;
		i = (NI)0;
		nimln_(3519, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI TM_XK56NhFOhNnnHqqeg9a8zTg_11;
				if (!(i_2 < ((NI) 8))) goto LA3;
				nimln_(3521, "system.nim");
				i = i_2;
				nimln_(34, "shadowcasting.nim");
				castOctant_m9aAGV5kdbzAn9ca9aQ8s3ePw(i, mask, (&(*walls)), heroPos, NIM_FALSE);
				nimln_(3522, "system.nim");
				TM_XK56NhFOhNnnHqqeg9a8zTg_11 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_XK56NhFOhNnnHqqeg9a8zTg_11);
			} LA3: ;
		}
	}
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, smoke_shadowcastingInit000)(void) {
	nimfr_("shadowcasting", "shadowcasting.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, smoke_shadowcastingDatInit000)(void) {
}

