/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -I"C:\Program Files\nim\nim-0.18.0\lib" -o "C:\Users\Quinn Freedman\workspace\nim\smoke\src\nimcache\smoke_clothingtypes.o" "C:\Users\Quinn Freedman\workspace\nim\smoke\src\nimcache\smoke_clothingtypes.c" */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_ClothingHead_h3YfKnLVYVYocWj5dIBPGw tyObject_ClothingHead_h3YfKnLVYVYocWj5dIBPGw;
typedef struct tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_ClothingBody_jYCMVvD4caXGho8aDSyHJQ tyObject_ClothingBody_jYCMVvD4caXGho8aDSyHJQ;
typedef struct tyObject_ClothingFeet_UGmkgjwjxmZBaRBpyJpGvw tyObject_ClothingFeet_UGmkgjwjxmZBaRBpyJpGvw;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg {
NimStringDesc* name;
};
struct tyObject_ClothingHead_h3YfKnLVYVYocWj5dIBPGw {
tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg stats;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_ClothingBody_jYCMVvD4caXGho8aDSyHJQ {
tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg stats;
};
struct tyObject_ClothingFeet_UGmkgjwjxmZBaRBpyJpGvw {
tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg stats;
};
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
TNimType NTI_h3YfKnLVYVYocWj5dIBPGw_;
TNimType NTI_zxet1nto49a9ae8pLlAU14cg_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_jYCMVvD4caXGho8aDSyHJQ_;
TNimType NTI_UGmkgjwjxmZBaRBpyJpGvw_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
NIM_EXTERNC N_NOINLINE(void, smoke_clothingtypesInit000)(void) {
	nimfr_("clothingtypes", "clothingtypes.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, smoke_clothingtypesDatInit000)(void) {
static TNimNode TM_y5kYS1VnjPo2xURbOFcVng_0[4];
NTI_h3YfKnLVYVYocWj5dIBPGw_.size = sizeof(tyObject_ClothingHead_h3YfKnLVYVYocWj5dIBPGw);
NTI_h3YfKnLVYVYocWj5dIBPGw_.kind = 18;
NTI_h3YfKnLVYVYocWj5dIBPGw_.base = 0;
NTI_h3YfKnLVYVYocWj5dIBPGw_.flags = 2;
NTI_zxet1nto49a9ae8pLlAU14cg_.size = sizeof(tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg);
NTI_zxet1nto49a9ae8pLlAU14cg_.kind = 18;
NTI_zxet1nto49a9ae8pLlAU14cg_.base = 0;
NTI_zxet1nto49a9ae8pLlAU14cg_.flags = 2;
TM_y5kYS1VnjPo2xURbOFcVng_0[1].kind = 1;
TM_y5kYS1VnjPo2xURbOFcVng_0[1].offset = offsetof(tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg, name);
TM_y5kYS1VnjPo2xURbOFcVng_0[1].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_y5kYS1VnjPo2xURbOFcVng_0[1].name = "name";
NTI_zxet1nto49a9ae8pLlAU14cg_.node = &TM_y5kYS1VnjPo2xURbOFcVng_0[1];
TM_y5kYS1VnjPo2xURbOFcVng_0[0].kind = 1;
TM_y5kYS1VnjPo2xURbOFcVng_0[0].offset = offsetof(tyObject_ClothingHead_h3YfKnLVYVYocWj5dIBPGw, stats);
TM_y5kYS1VnjPo2xURbOFcVng_0[0].typ = (&NTI_zxet1nto49a9ae8pLlAU14cg_);
TM_y5kYS1VnjPo2xURbOFcVng_0[0].name = "stats";
NTI_h3YfKnLVYVYocWj5dIBPGw_.node = &TM_y5kYS1VnjPo2xURbOFcVng_0[0];
NTI_jYCMVvD4caXGho8aDSyHJQ_.size = sizeof(tyObject_ClothingBody_jYCMVvD4caXGho8aDSyHJQ);
NTI_jYCMVvD4caXGho8aDSyHJQ_.kind = 18;
NTI_jYCMVvD4caXGho8aDSyHJQ_.base = 0;
NTI_jYCMVvD4caXGho8aDSyHJQ_.flags = 2;
TM_y5kYS1VnjPo2xURbOFcVng_0[2].kind = 1;
TM_y5kYS1VnjPo2xURbOFcVng_0[2].offset = offsetof(tyObject_ClothingBody_jYCMVvD4caXGho8aDSyHJQ, stats);
TM_y5kYS1VnjPo2xURbOFcVng_0[2].typ = (&NTI_zxet1nto49a9ae8pLlAU14cg_);
TM_y5kYS1VnjPo2xURbOFcVng_0[2].name = "stats";
NTI_jYCMVvD4caXGho8aDSyHJQ_.node = &TM_y5kYS1VnjPo2xURbOFcVng_0[2];
NTI_UGmkgjwjxmZBaRBpyJpGvw_.size = sizeof(tyObject_ClothingFeet_UGmkgjwjxmZBaRBpyJpGvw);
NTI_UGmkgjwjxmZBaRBpyJpGvw_.kind = 18;
NTI_UGmkgjwjxmZBaRBpyJpGvw_.base = 0;
NTI_UGmkgjwjxmZBaRBpyJpGvw_.flags = 2;
TM_y5kYS1VnjPo2xURbOFcVng_0[3].kind = 1;
TM_y5kYS1VnjPo2xURbOFcVng_0[3].offset = offsetof(tyObject_ClothingFeet_UGmkgjwjxmZBaRBpyJpGvw, stats);
TM_y5kYS1VnjPo2xURbOFcVng_0[3].typ = (&NTI_zxet1nto49a9ae8pLlAU14cg_);
TM_y5kYS1VnjPo2xURbOFcVng_0[3].name = "stats";
NTI_UGmkgjwjxmZBaRBpyJpGvw_.node = &TM_y5kYS1VnjPo2xURbOFcVng_0[3];
}

