/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -I"C:\Program Files\nim\nim-0.18.0\lib" -o "C:\Users\Quinn Freedman\workspace\nim\smoke\src\nimcache\smoke_gamestate.o" "C:\Users\Quinn Freedman\workspace\nim\smoke\src\nimcache\smoke_gamestate.c" */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ;
typedef struct tyObject_Matrix_IUzOSceCjOZ59cvd9c09cGiMw tyObject_Matrix_IUzOSceCjOZ59cvd9c09cGiMw;
typedef struct tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g;
typedef struct tySequence_qwqHTkRvwhrRyENtudHQ7g tySequence_qwqHTkRvwhrRyENtudHQ7g;
typedef struct tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg;
typedef struct tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA;
typedef struct tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg;
typedef struct tyObject_GameResources_ooM6Pmr7S9aRM2IrojeLpTg tyObject_GameResources_ooM6Pmr7S9aRM2IrojeLpTg;
typedef struct tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw;
typedef struct tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ;
typedef struct TGenericSeq TGenericSeq;
struct tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g {
NI x;
NI y;
};
struct tyObject_Matrix_IUzOSceCjOZ59cvd9c09cGiMw {
NI width;
NI height;
tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g offset;
tySequence_qwqHTkRvwhrRyENtudHQ7g* data;
};
struct tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA {
NF x;
NF y;
};
typedef NU8 tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg;
typedef NU8 tyEnum_Race_wN6IdQU5M5xJLM35A76jlQ;
typedef NU8 tyEnum_Sex_fZXzEuE89cG49aK9cXfwfCxeQ;
struct tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg {
tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g currentTile;
tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g nextTile;
tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA actualPos;
tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg facing;
NF speed;
tyEnum_Race_wN6IdQU5M5xJLM35A76jlQ race;
tyEnum_Sex_fZXzEuE89cG49aK9cXfwfCxeQ sex;
};
struct tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ {
tyObject_Matrix_IUzOSceCjOZ59cvd9c09cGiMw map;
tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg playerCharacter;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NIM_BOOL tyArray_k64wcrcoLEGgK5bVTvG2WA[6];
struct tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ {
int Field0;
int Field1;
int Field2;
int Field3;
};
typedef tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ tyArray_5DS7xhk7iTcg7Sx9cHw9biag[32];
struct tyObject_GameResources_ooM6Pmr7S9aRM2IrojeLpTg {
tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* mapTexture;
tyArray_5DS7xhk7iTcg7Sx9cHw9biag mapTiles;
tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* baseSpriteFemaleHuman;
tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* baseSpriteMaleHuman;
};
struct tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA {
tyArray_k64wcrcoLEGgK5bVTvG2WA inputs;
tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer;
tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ gameState;
tyObject_GameResources_ooM6Pmr7S9aRM2IrojeLpTg resources;
};
typedef NU8 tyEnum_Input_HkmkensvbmBMoEqXX3PFKw;
struct TGenericSeq {
NI len;
NI reserved;
};
struct tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg {
char dummy;
};
struct tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw {
char dummy;
};
struct tySequence_qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, initGamestate_FNlPPl39aiQFG5ZxCMgW9bUw)(tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg, newCharacter_Ia3w0EG3EIpjyMYcAfcqRA)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g pos, NF speed, tyEnum_Race_wN6IdQU5M5xJLM35A76jlQ race, tyEnum_Sex_fZXzEuE89cG49aK9cXfwfCxeQ sex);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g, v_g7Ok4O0iyLEmW9bny8ZknmA)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(void, newMatrix_Bg3jv86WxJycMRiaTgSRZw)(NI width, NI height, tyObject_Matrix_IUzOSceCjOZ59cvd9c09cGiMw* Result);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, loop_Z9bGN9cEjwwM1MosnoQKTduA)(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA** self, NF dt);
N_LIB_PRIVATE N_NIMCALL(void, move_vRBvJ39aGLz6uMrHDS0JOhw)(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg* self, tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg dir);
N_LIB_PRIVATE N_NIMCALL(void, update_pBfJunJAWPEnvkt2lnqkcA)(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg* self, NF dt);
N_LIB_PRIVATE N_NIMCALL(tySequence_qwqHTkRvwhrRyENtudHQ7g*, newSeq_vg7LhJDfsuQYl9cZfOCH1Fw)(NI len);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_lJGwzzOtEj8PUQVSnppB6w)(void* p, NI op);
TNimType NTI_np3Rx8N215Y1kfBowS8mPQ_;
extern TNimType NTI_IUzOSceCjOZ59cvd9c09cGiMw_;
extern TNimType NTI_z7sEl7rGLIEtgyeCSL9aOwg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_CtGi8Xr9b12gKxEZURFqedA_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
TNimType NTI_k64wcrcoLEGgK5bVTvG2WA_;
extern TNimType NTI_7lSakCSU4VtJLR9aqvUx9buA_;
extern TNimType NTI_ooM6Pmr7S9aRM2IrojeLpTg_;
TNimType NTI_lJGwzzOtEj8PUQVSnppB6w_;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(void, initGamestate_FNlPPl39aiQFG5ZxCMgW9bUw)(tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ* Result) {
	tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g T1_;
	nimfr_("initGamestate", "gamestate.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_np3Rx8N215Y1kfBowS8mPQ_));
	nimln_(24, "gamestate.nim");
	T1_ = v_g7Ok4O0iyLEmW9bny8ZknmA(((NI) 0), ((NI) 0));
	(*Result).playerCharacter = newCharacter_Ia3w0EG3EIpjyMYcAfcqRA(T1_, 1.5000000000000000e+000, ((tyEnum_Race_wN6IdQU5M5xJLM35A76jlQ) 0), ((tyEnum_Sex_fZXzEuE89cG49aK9cXfwfCxeQ) 0));
	nimln_(25, "gamestate.nim");
	newMatrix_Bg3jv86WxJycMRiaTgSRZw(((NI) 10), ((NI) 10), (&(*Result).map));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, loop_Z9bGN9cEjwwM1MosnoQKTduA)(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA** self, NF dt) {
	nimfr_("loop", "gamestate.nim");
	nimln_(29, "gamestate.nim");
	{
		if (!(*(*self)).inputs[(((tyEnum_Input_HkmkensvbmBMoEqXX3PFKw) 3))- 0]) goto LA3_;
		nimln_(30, "gamestate.nim");
		move_vRBvJ39aGLz6uMrHDS0JOhw((&(*(*self)).gameState.playerCharacter), ((tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg) 0));
	}
	LA3_: ;
	nimln_(31, "gamestate.nim");
	{
		if (!(*(*self)).inputs[(((tyEnum_Input_HkmkensvbmBMoEqXX3PFKw) 4))- 0]) goto LA7_;
		nimln_(32, "gamestate.nim");
		move_vRBvJ39aGLz6uMrHDS0JOhw((&(*(*self)).gameState.playerCharacter), ((tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg) 1));
	}
	LA7_: ;
	nimln_(33, "gamestate.nim");
	{
		if (!(*(*self)).inputs[(((tyEnum_Input_HkmkensvbmBMoEqXX3PFKw) 1))- 0]) goto LA11_;
		nimln_(34, "gamestate.nim");
		move_vRBvJ39aGLz6uMrHDS0JOhw((&(*(*self)).gameState.playerCharacter), ((tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg) 2));
	}
	LA11_: ;
	nimln_(35, "gamestate.nim");
	{
		if (!(*(*self)).inputs[(((tyEnum_Input_HkmkensvbmBMoEqXX3PFKw) 2))- 0]) goto LA15_;
		nimln_(36, "gamestate.nim");
		move_vRBvJ39aGLz6uMrHDS0JOhw((&(*(*self)).gameState.playerCharacter), ((tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg) 3));
	}
	LA15_: ;
	nimln_(38, "gamestate.nim");
	update_pBfJunJAWPEnvkt2lnqkcA((&(*(*self)).gameState.playerCharacter), dt);
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_lJGwzzOtEj8PUQVSnppB6w)(void* p, NI op) {
	tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA* a;
	NI T1_;
	NI T2_;
	a = (tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA*)p;
	T1_ = (NI)0;
	nimGCvisit((void*)(*a).gameState.map.data, op);
	T2_ = (NI)0;
}
NIM_EXTERNC N_NOINLINE(void, smoke_gamestateInit000)(void) {
	nimfr_("gamestate", "gamestate.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, smoke_gamestateDatInit000)(void) {
static TNimNode* TM_Q01Ygr8gIHg9bmY3vO9anPCQ_2[2];
static TNimNode* TM_Q01Ygr8gIHg9bmY3vO9anPCQ_3[4];
static TNimNode TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[8];
NTI_np3Rx8N215Y1kfBowS8mPQ_.size = sizeof(tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ);
NTI_np3Rx8N215Y1kfBowS8mPQ_.kind = 18;
NTI_np3Rx8N215Y1kfBowS8mPQ_.base = 0;
NTI_np3Rx8N215Y1kfBowS8mPQ_.flags = 2;
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_2[0] = &TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[1];
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[1].kind = 1;
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[1].offset = offsetof(tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ, map);
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[1].typ = (&NTI_IUzOSceCjOZ59cvd9c09cGiMw_);
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[1].name = "map";
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_2[1] = &TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[2];
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[2].kind = 1;
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[2].offset = offsetof(tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ, playerCharacter);
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[2].typ = (&NTI_z7sEl7rGLIEtgyeCSL9aOwg_);
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[2].name = "playerCharacter";
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[0].len = 2; TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[0].kind = 2; TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[0].sons = &TM_Q01Ygr8gIHg9bmY3vO9anPCQ_2[0];
NTI_np3Rx8N215Y1kfBowS8mPQ_.node = &TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[0];
NTI_CtGi8Xr9b12gKxEZURFqedA_.size = sizeof(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA);
NTI_CtGi8Xr9b12gKxEZURFqedA_.kind = 18;
NTI_CtGi8Xr9b12gKxEZURFqedA_.base = 0;
NTI_CtGi8Xr9b12gKxEZURFqedA_.flags = 2;
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_3[0] = &TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[4];
NTI_k64wcrcoLEGgK5bVTvG2WA_.size = sizeof(tyArray_k64wcrcoLEGgK5bVTvG2WA);
NTI_k64wcrcoLEGgK5bVTvG2WA_.kind = 16;
NTI_k64wcrcoLEGgK5bVTvG2WA_.base = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
NTI_k64wcrcoLEGgK5bVTvG2WA_.flags = 3;
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[4].kind = 1;
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[4].offset = offsetof(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA, inputs);
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[4].typ = (&NTI_k64wcrcoLEGgK5bVTvG2WA_);
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[4].name = "inputs";
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_3[1] = &TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[5];
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[5].kind = 1;
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[5].offset = offsetof(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA, renderer);
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[5].typ = (&NTI_7lSakCSU4VtJLR9aqvUx9buA_);
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[5].name = "renderer";
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_3[2] = &TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[6];
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[6].kind = 1;
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[6].offset = offsetof(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA, gameState);
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[6].typ = (&NTI_np3Rx8N215Y1kfBowS8mPQ_);
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[6].name = "gameState";
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_3[3] = &TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[7];
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[7].kind = 1;
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[7].offset = offsetof(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA, resources);
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[7].typ = (&NTI_ooM6Pmr7S9aRM2IrojeLpTg_);
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[7].name = "resources";
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[3].len = 4; TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[3].kind = 2; TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[3].sons = &TM_Q01Ygr8gIHg9bmY3vO9anPCQ_3[0];
NTI_CtGi8Xr9b12gKxEZURFqedA_.node = &TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[3];
NTI_lJGwzzOtEj8PUQVSnppB6w_.size = sizeof(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA*);
NTI_lJGwzzOtEj8PUQVSnppB6w_.kind = 22;
NTI_lJGwzzOtEj8PUQVSnppB6w_.base = (&NTI_CtGi8Xr9b12gKxEZURFqedA_);
NTI_lJGwzzOtEj8PUQVSnppB6w_.flags = 2;
NTI_lJGwzzOtEj8PUQVSnppB6w_.marker = Marker_tyRef_lJGwzzOtEj8PUQVSnppB6w;
}

