/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -I"C:\Program Files\nim\nim-0.18.0\lib" -o "C:\Users\Quinn Freedman\workspace\nim\smoke\src\nimcache\smoke_smoke.o" "C:\Users\Quinn Freedman\workspace\nim\smoke\src\nimcache\smoke_smoke.c" */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <setjmp.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA;
typedef struct tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug;
typedef struct tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg;
typedef struct tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ;
typedef struct tyObject_Matrix_5jfXleRjKMzj7p29cba2i9bg tyObject_Matrix_5jfXleRjKMzj7p29cba2i9bg;
typedef struct tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g;
typedef struct tySequence_6MHxSSkCYafnfGYzxyCqtA tySequence_6MHxSSkCYafnfGYzxyCqtA;
typedef struct tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw;
typedef struct tySequence_shxop0zPIs5Ec3k71aCLuQ tySequence_shxop0zPIs5Ec3k71aCLuQ;
typedef struct tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg;
typedef struct tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA;
typedef struct tyObject_ItemSet_q6qi9bPVWXyspg9bTRkyuyXw tyObject_ItemSet_q6qi9bPVWXyspg9bTRkyuyXw;
typedef struct tyObject_ClothingHead_h3YfKnLVYVYocWj5dIBPGw tyObject_ClothingHead_h3YfKnLVYVYocWj5dIBPGw;
typedef struct tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_ClothingBody_jYCMVvD4caXGho8aDSyHJQ tyObject_ClothingBody_jYCMVvD4caXGho8aDSyHJQ;
typedef struct tyObject_ClothingFeet_UGmkgjwjxmZBaRBpyJpGvw tyObject_ClothingFeet_UGmkgjwjxmZBaRBpyJpGvw;
typedef struct tyObject_KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ tyObject_KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ;
typedef struct tyObject_KeySym_y3t7PyKCT9aYLDh9bLHT3UPw tyObject_KeySym_y3t7PyKCT9aYLDh9bLHT3UPw;
typedef struct tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w;
typedef struct tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef NU8 tyEnum_Input_HkmkensvbmBMoEqXX3PFKw;
typedef NI32 tyEnum_Scancode_ZC4j1APU9aAJPXuZfLFUG0w;
typedef NI32 tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w;
typedef NU8 tyArray_Y1pDC6KIrpu9aJMBN9aOQMhw[52];
struct tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug {
tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w kind;
tyArray_Y1pDC6KIrpu9aJMBN9aOQMhw padding;
};
typedef NI32 tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg;
typedef N_CDECL_PTR(tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg, tyProc_b9aXpKFbsyZ0PIk3aYRVCAA) (tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug* event);
typedef NIM_BOOL tyArray_k64wcrcoLEGgK5bVTvG2WA[6];
struct tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g {
NI x;
NI y;
};
struct tyObject_Matrix_5jfXleRjKMzj7p29cba2i9bg {
NI width;
NI height;
tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g offset;
tySequence_6MHxSSkCYafnfGYzxyCqtA* data;
};
struct tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw {
NI width;
NI height;
tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g offset;
tySequence_shxop0zPIs5Ec3k71aCLuQ* data;
};
struct tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA {
NF x;
NF y;
};
typedef NU8 tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg;
typedef NU8 tyEnum_Race_wN6IdQU5M5xJLM35A76jlQ;
typedef NU8 tyEnum_Sex_fZXzEuE89cG49aK9cXfwfCxeQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg {
NimStringDesc* name;
};
struct tyObject_ClothingHead_h3YfKnLVYVYocWj5dIBPGw {
tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg stats;
};
struct tyObject_ClothingBody_jYCMVvD4caXGho8aDSyHJQ {
tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg stats;
};
struct tyObject_ClothingFeet_UGmkgjwjxmZBaRBpyJpGvw {
tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg stats;
};
struct tyObject_ItemSet_q6qi9bPVWXyspg9bTRkyuyXw {
tyObject_ClothingHead_h3YfKnLVYVYocWj5dIBPGw head;
tyObject_ClothingBody_jYCMVvD4caXGho8aDSyHJQ body;
tyObject_ClothingFeet_UGmkgjwjxmZBaRBpyJpGvw legs;
};
typedef NU8 tyEnum_TextureAlias_6sotYNRMaoTgzBzqkJyyLQ;
struct tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg {
tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g currentTile;
tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g nextTile;
tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA actualPos;
tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg facing;
NF speed;
tyEnum_Race_wN6IdQU5M5xJLM35A76jlQ race;
tyEnum_Sex_fZXzEuE89cG49aK9cXfwfCxeQ sex;
tyObject_ItemSet_q6qi9bPVWXyspg9bTRkyuyXw items;
tyEnum_TextureAlias_6sotYNRMaoTgzBzqkJyyLQ spritesheet;
};
struct tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ {
tyObject_Matrix_5jfXleRjKMzj7p29cba2i9bg mapTextures;
tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw walls;
tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg playerCharacter;
};
struct tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA {
tyArray_k64wcrcoLEGgK5bVTvG2WA inputs;
tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer;
tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ gameState;
};
struct tyObject_KeySym_y3t7PyKCT9aYLDh9bLHT3UPw {
tyEnum_Scancode_ZC4j1APU9aAJPXuZfLFUG0w scancode;
int sym;
NI16 modstate;
int unicode;
};
struct tyObject_KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ {
tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w kind;
NU32 timestamp;
NU32 windowID;
NU8 state;
NIM_BOOL repeat;
NU8 pad1;
NU8 pad2;
tyObject_KeySym_y3t7PyKCT9aYLDh9bLHT3UPw keysym;
};
typedef N_CDECL_PTR(int, tyProc_zHpDbFN4o9bvP9cAphXAUHXg) (tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer);
typedef N_CDECL_PTR(void, tyProc_9a8AalbnAaIxTUMpzQQqpjw) (tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer);
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
typedef NI32 tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw;
typedef N_CDECL_PTR(tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw, tyProc_fvOXafK39cW5YZA9b9bzinu9cw) (int flags);
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg {
  Exception Sup;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(NCSTRING, tyProc_09bvyvHFtWbkzL5AHgf0bKw) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef N_CDECL_PTR(int, tyProc_4hSZquf3VZZvlELaYshEWg) (int flags);
typedef N_CDECL_PTR(NIM_BOOL, tyProc_CS9bxA1KE4RHFQ1vMCkCBmg) (NCSTRING name, NCSTRING value);
typedef N_CDECL_PTR(tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w*, tyProc_1K9aSViCbSUpZMtRI9aw9a2Rg) (NCSTRING title, int x, int y, int w, int h, NU32 flags);
typedef N_CDECL_PTR(tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg*, tyProc_eGPD9aEHv9b8sVQMCQaPsYkg) (tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window, int index, int flags);
typedef N_CDECL_PTR(tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw, tyProc_BzAZji9bzvN1k9ae25rIlb8A) (tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, tyProc_FdNQc14l0KrdlpQKlTQjEA) (tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, int w, int h);
typedef N_CDECL_PTR(void, tyProc_T629bWTbvDFNyKAaO0BGGIQ) (tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window);
typedef N_CDECL_PTR(void, tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
struct tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg {
char dummy;
};
struct tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ {
int Field0;
int Field1;
int Field2;
int Field3;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w {
char dummy;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_6MHxSSkCYafnfGYzxyCqtA {
  TGenericSeq Sup;
  tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ data[SEQ_DECL_SIZE];
};
struct tySequence_shxop0zPIs5Ec3k71aCLuQ {
  TGenericSeq Sup;
  NIM_BOOL data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(tyEnum_Input_HkmkensvbmBMoEqXX3PFKw, toInput_sW56DJVBY2IuMjCIsI5tPQ)(tyEnum_Scancode_ZC4j1APU9aAJPXuZfLFUG0w key);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, handleInput_4cFc3ApldCyqXVMMnn1bmQ)(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA** game);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, toBool_3fq5Y9cfgYx8q7J9ba6TTYbQ)(tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg some);
N_LIB_PRIVATE N_NIMCALL(tyObject_KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ*, key_Sy9cYLza36NW1QN9asfW9a0LA)(tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug* event);
N_LIB_PRIVATE N_NIMCALL(void, render_4cFc3ApldCyqXVMMnn1bmQ_2)(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA** game);
N_LIB_PRIVATE N_NIMCALL(void, renderGameFrame_DNr2pOUK8Aw01XldiYBEiA)(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA** game);
N_LIB_PRIVATE N_NIMCALL(void, main_bWnkIoWyFFnjlYj9a9baJQYw)(void);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosgetCurrentDir)(void);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, toBool_9bg9codirrpaPKZJuSwGJgEg)(tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw some);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_yEsavQFTBQGpgLZ3fCM9aPA)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_LIB_PRIVATE N_NIMCALL(void, initTextures_5jhsfEp2uQLg0uKv65KfVg)(tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer);
N_LIB_PRIVATE N_NIMCALL(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA*, initGameData_SMOesfyeK6X3txgLgpEMOQ)(tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer);
N_LIB_PRIVATE N_NIMCALL(NF, ntepochTime)(void);
N_LIB_PRIVATE N_NIMCALL(void, loop_Z9bGN9cEjwwM1MosnoQKTduA)(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA** self, NF dt);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, reraiseException)(void);
static N_INLINE(void, destroy_sFvfWODyHxg46OuBtGyU8Qsmoke)(tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2Init000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_imageInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_imageDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, smoke_vectorInit000)(void);
NIM_EXTERNC N_NOINLINE(void, smoke_vectorDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, smoke_matrixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, smoke_matrixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_randomInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_randomDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, smoke_directionInit000)(void);
NIM_EXTERNC N_NOINLINE(void, smoke_directionDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, smoke_constantsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, smoke_constantsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, smoke_utilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, smoke_utilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, smoke_texturesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, smoke_texturesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, smoke_clothingtypesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, smoke_clothingtypesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, smoke_characterInit000)(void);
NIM_EXTERNC N_NOINLINE(void, smoke_characterDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, smoke_gamestateInit000)(void);
NIM_EXTERNC N_NOINLINE(void, smoke_gamestateDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, smoke_rectangleInit000)(void);
NIM_EXTERNC N_NOINLINE(void, smoke_rectangleDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, smoke_shadowcastingInit000)(void);
NIM_EXTERNC N_NOINLINE(void, smoke_shadowcastingDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, smoke_renderInit000)(void);
NIM_EXTERNC N_NOINLINE(void, smoke_renderDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, smokeDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug defaultEvent_LbtYyFPe9bpTC9bKZ8rWJeKQ;
extern tyProc_b9aXpKFbsyZ0PIk3aYRVCAA Dl_147605_;
extern tyProc_zHpDbFN4o9bvP9cAphXAUHXg Dl_147017_;
extern tyProc_9a8AalbnAaIxTUMpzQQqpjw Dl_147036_;
extern tyProc_fvOXafK39cW5YZA9b9bzinu9cw Dl_146765_;
extern TNimType NTI_bAvOj2UcojKN87yAQLs0aw_;
TNimType NTI_HEToztgn9a0zVfyFTQj1vQg_;
TNimType NTI_yEsavQFTBQGpgLZ3fCM9aPA_;
extern tyProc_09bvyvHFtWbkzL5AHgf0bKw Dl_147654_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
extern tyProc_4hSZquf3VZZvlELaYshEWg Dl_149604_;
extern tyProc_CS9bxA1KE4RHFQ1vMCkCBmg Dl_148013_;
extern tyProc_1K9aSViCbSUpZMtRI9aw9a2Rg Dl_147356_;
extern tyProc_eGPD9aEHv9b8sVQMCQaPsYkg Dl_146811_;
extern tyProc_BzAZji9bzvN1k9ae25rIlb8A Dl_146617_;
extern tyProc_FdNQc14l0KrdlpQKlTQjEA Dl_146606_;
extern tyProc_9a8AalbnAaIxTUMpzQQqpjw Dl_146648_;
extern tyProc_T629bWTbvDFNyKAaO0BGGIQ Dl_147388_;
extern tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_149607_;
extern tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_146777_;
STRING_LITERAL(TM_bBfdi46nQ4ev68Uhq10y0A_2, "Starting game from directory: ", 30);
STRING_LITERAL(TM_bBfdi46nQ4ev68Uhq10y0A_3, "SDL2 initialization failed", 26);
STRING_LITERAL(TM_bBfdi46nQ4ev68Uhq10y0A_4, ", SDL error: ", 13);
STRING_LITERAL(TM_bBfdi46nQ4ev68Uhq10y0A_6, "SDL2 Image initialization failed", 32);
STRING_LITERAL(TM_bBfdi46nQ4ev68Uhq10y0A_8, "Linear texture filtering could not be enabled", 45);
STRING_LITERAL(TM_bBfdi46nQ4ev68Uhq10y0A_9, "Window could not be created", 27);
STRING_LITERAL(TM_bBfdi46nQ4ev68Uhq10y0A_11, "Renderer could not be created", 29);
STRING_LITERAL(TM_bBfdi46nQ4ev68Uhq10y0A_14, "Warning: unable to set renderer logical size", 44);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_bBfdi46nQ4ev68Uhq10y0A_13 = {((NimStringDesc*) &TM_bBfdi46nQ4ev68Uhq10y0A_14)}
;
STRING_LITERAL(TM_bBfdi46nQ4ev68Uhq10y0A_16, "Warning: unable to set texture filtering mode", 45);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_bBfdi46nQ4ev68Uhq10y0A_15 = {((NimStringDesc*) &TM_bBfdi46nQ4ev68Uhq10y0A_16)}
;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_Input_HkmkensvbmBMoEqXX3PFKw, toInput_sW56DJVBY2IuMjCIsI5tPQ)(tyEnum_Scancode_ZC4j1APU9aAJPXuZfLFUG0w key) {
	tyEnum_Input_HkmkensvbmBMoEqXX3PFKw result;
	nimfr_("toInput", "smoke.nim");
	result = (tyEnum_Input_HkmkensvbmBMoEqXX3PFKw)0;
	nimln_(22, "smoke.nim");
	switch (key) {
	case ((tyEnum_Scancode_ZC4j1APU9aAJPXuZfLFUG0w) 4):
	{
		result = ((tyEnum_Input_HkmkensvbmBMoEqXX3PFKw) 1);
	}
	break;
	case ((tyEnum_Scancode_ZC4j1APU9aAJPXuZfLFUG0w) 7):
	{
		result = ((tyEnum_Input_HkmkensvbmBMoEqXX3PFKw) 2);
	}
	break;
	case ((tyEnum_Scancode_ZC4j1APU9aAJPXuZfLFUG0w) 26):
	{
		result = ((tyEnum_Input_HkmkensvbmBMoEqXX3PFKw) 3);
	}
	break;
	case ((tyEnum_Scancode_ZC4j1APU9aAJPXuZfLFUG0w) 22):
	{
		result = ((tyEnum_Input_HkmkensvbmBMoEqXX3PFKw) 4);
	}
	break;
	case ((tyEnum_Scancode_ZC4j1APU9aAJPXuZfLFUG0w) 80):
	{
		result = ((tyEnum_Input_HkmkensvbmBMoEqXX3PFKw) 1);
	}
	break;
	case ((tyEnum_Scancode_ZC4j1APU9aAJPXuZfLFUG0w) 79):
	{
		result = ((tyEnum_Input_HkmkensvbmBMoEqXX3PFKw) 2);
	}
	break;
	case ((tyEnum_Scancode_ZC4j1APU9aAJPXuZfLFUG0w) 82):
	{
		result = ((tyEnum_Input_HkmkensvbmBMoEqXX3PFKw) 3);
	}
	break;
	case ((tyEnum_Scancode_ZC4j1APU9aAJPXuZfLFUG0w) 81):
	{
		result = ((tyEnum_Input_HkmkensvbmBMoEqXX3PFKw) 4);
	}
	break;
	case ((tyEnum_Scancode_ZC4j1APU9aAJPXuZfLFUG0w) 41):
	{
		result = ((tyEnum_Input_HkmkensvbmBMoEqXX3PFKw) 5);
	}
	break;
	default:
	{
		result = ((tyEnum_Input_HkmkensvbmBMoEqXX3PFKw) 0);
	}
	break;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, handleInput_4cFc3ApldCyqXVMMnn1bmQ)(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA** game) {
	tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug event;
	nimfr_("handleInput", "smoke.nim");
	nimln_(35, "smoke.nim");
	event = defaultEvent_LbtYyFPe9bpTC9bKZ8rWJeKQ;
	{
		nimln_(36, "smoke.nim");
		while (1) {
			tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg T3_;
			NIM_BOOL T4_;
			T3_ = (tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg)0;
			T3_ = Dl_147605_((&event));
			T4_ = (NIM_BOOL)0;
			T4_ = toBool_3fq5Y9cfgYx8q7J9ba6TTYbQ(T3_);
			if (!T4_) goto LA2;
			nimln_(37, "smoke.nim");
			switch (event.kind) {
			case ((tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 256):
			{
				nimln_(39, "smoke.nim");
				(*(*game)).inputs[(((tyEnum_Input_HkmkensvbmBMoEqXX3PFKw) 5))- 0] = NIM_TRUE;
			}
			break;
			case ((tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 768):
			{
				tyObject_KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ* T7_;
				tyEnum_Input_HkmkensvbmBMoEqXX3PFKw T8_;
				nimln_(41, "smoke.nim");
				T7_ = (tyObject_KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ*)0;
				T7_ = key_Sy9cYLza36NW1QN9asfW9a0LA((&event));
				T8_ = (tyEnum_Input_HkmkensvbmBMoEqXX3PFKw)0;
				T8_ = toInput_sW56DJVBY2IuMjCIsI5tPQ((*T7_).keysym.scancode);
				(*(*game)).inputs[(T8_)- 0] = NIM_TRUE;
			}
			break;
			case ((tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 769):
			{
				tyObject_KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ* T10_;
				tyEnum_Input_HkmkensvbmBMoEqXX3PFKw T11_;
				nimln_(43, "smoke.nim");
				T10_ = (tyObject_KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ*)0;
				T10_ = key_Sy9cYLza36NW1QN9asfW9a0LA((&event));
				T11_ = (tyEnum_Input_HkmkensvbmBMoEqXX3PFKw)0;
				T11_ = toInput_sW56DJVBY2IuMjCIsI5tPQ((*T10_).keysym.scancode);
				(*(*game)).inputs[(T11_)- 0] = NIM_FALSE;
			}
			break;
			default:
			{
			}
			break;
			}
		} LA2: ;
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, render_4cFc3ApldCyqXVMMnn1bmQ_2)(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA** game) {
	int T1_;
	nimfr_("render", "smoke.nim");
	nimln_(49, "smoke.nim");
	T1_ = (int)0;
	T1_ = Dl_147017_((*(*game)).renderer);
	nimln_(51, "smoke.nim");
	renderGameFrame_DNr2pOUK8Aw01XldiYBEiA(game);
	nimln_(53, "smoke.nim");
	Dl_147036_((*(*game)).renderer);
	popFrame();
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}
static N_NIMCALL(void, Marker_tyRef_yEsavQFTBQGpgLZ3fCM9aPA)(void* p, NI op) {
	tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg* a;
	a = (tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg*)p;
	nimGCvisit((void*)(*a).Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.message, op);
	nimGCvisit((void*)(*a).Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.up, op);
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

static N_INLINE(void, destroy_sFvfWODyHxg46OuBtGyU8Qsmoke)(tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window) {
	nimfr_("destroy", "sdl2.nim");
	nimln_(1742, "sdl2.nim");
	Dl_147388_(window);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, main_bWnkIoWyFFnjlYj9a9baJQYw)(void) {
	tyArray_nHXaesL0DJZHyVS07ARPRA T1_;
	NimStringDesc* T2_;
	NimStringDesc* T3_;
	TSafePoint TM_bBfdi46nQ4ev68Uhq10y0A_5;
	nimfr_("main", "smoke.nim");
	nimln_(57, "smoke.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	T2_ = (NimStringDesc*)0;
	T3_ = (NimStringDesc*)0;
	T3_ = nosgetCurrentDir();
	T2_ = rawNewString(T3_->Sup.len + 30);
appendString(T2_, ((NimStringDesc*) &TM_bBfdi46nQ4ev68Uhq10y0A_2));
appendString(T2_, T3_);
	T1_[0] = T2_;
	echoBinSafe(T1_, 1);
	nimln_(59, "smoke.nim");
	{
		tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw T6_;
		NIM_BOOL T7_;
		tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg* e;
		NimStringDesc* T10_;
		NCSTRING T11_;
		NimStringDesc* T12_;
		T6_ = (tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw)0;
		T6_ = Dl_146765_(((int) 16417));
		T7_ = (NIM_BOOL)0;
		T7_ = toBool_9bg9codirrpaPKZJuSwGJgEg(T6_);
		if (!!(T7_)) goto LA8_;
		e = (tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg*)0;
		nimln_(2811, "system.nim");
		e = (tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg*) newObj((&NTI_yEsavQFTBQGpgLZ3fCM9aPA_), sizeof(tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg));
		(*e).Sup.Sup.m_type = (&NTI_HEToztgn9a0zVfyFTQj1vQg_);
		nimln_(60, "smoke.nim");
		T10_ = (NimStringDesc*)0;
		nimln_(18, "smoke.nim");
		T11_ = (NCSTRING)0;
		T11_ = Dl_147654_();
		T12_ = (NimStringDesc*)0;
		T12_ = cstrToNimstr(T11_);
		T10_ = rawNewString(((NimStringDesc*) &TM_bBfdi46nQ4ev68Uhq10y0A_3)->Sup.len + T12_->Sup.len + 13);
appendString(T10_, ((NimStringDesc*) &TM_bBfdi46nQ4ev68Uhq10y0A_3));
appendString(T10_, ((NimStringDesc*) &TM_bBfdi46nQ4ev68Uhq10y0A_4));
appendString(T10_, T12_);
		asgnRefNoCycle((void**) (&(*e).Sup.message), T10_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(17, "smoke.nim");
		raiseException((Exception*)e, "SDLException");
	}
	LA8_: ;
	nimln_(64, "smoke.nim");
	pushSafePoint(&TM_bBfdi46nQ4ev68Uhq10y0A_5);
	TM_bBfdi46nQ4ev68Uhq10y0A_5.status = setjmp(TM_bBfdi46nQ4ev68Uhq10y0A_5.context);
	if (TM_bBfdi46nQ4ev68Uhq10y0A_5.status == 0) {
		TSafePoint TM_bBfdi46nQ4ev68Uhq10y0A_7;
		nimln_(67, "smoke.nim");
		{
			int T16_;
			tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg* volatile e_2;
			NimStringDesc* T19_;
			NCSTRING T20_;
			NimStringDesc* T21_;
			nimln_(398, "system.nim");
			nimln_(67, "smoke.nim");
			T16_ = (int)0;
			T16_ = Dl_149604_(((int) 2));
			if (!!((T16_ == ((int) 2)))) goto LA17_;
			e_2 = (tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg*)0;
			nimln_(2811, "system.nim");
			e_2 = (tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg*) newObj((&NTI_yEsavQFTBQGpgLZ3fCM9aPA_), sizeof(tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg));
			(*e_2).Sup.Sup.m_type = (&NTI_HEToztgn9a0zVfyFTQj1vQg_);
			nimln_(68, "smoke.nim");
			T19_ = (NimStringDesc*)0;
			nimln_(18, "smoke.nim");
			T20_ = (NCSTRING)0;
			T20_ = Dl_147654_();
			T21_ = (NimStringDesc*)0;
			T21_ = cstrToNimstr(T20_);
			T19_ = rawNewString(((NimStringDesc*) &TM_bBfdi46nQ4ev68Uhq10y0A_6)->Sup.len + T21_->Sup.len + 13);
appendString(T19_, ((NimStringDesc*) &TM_bBfdi46nQ4ev68Uhq10y0A_6));
appendString(T19_, ((NimStringDesc*) &TM_bBfdi46nQ4ev68Uhq10y0A_4));
appendString(T19_, T21_);
			asgnRefNoCycle((void**) (&(*e_2).Sup.message), T19_);
			nimln_(2806, "system.nim");
			asgnRef((void**) (&(*e_2).Sup.parent), NIM_NIL);
			nimln_(17, "smoke.nim");
			raiseException((Exception*)e_2, "SDLException");
		}
		LA17_: ;
		nimln_(69, "smoke.nim");
		pushSafePoint(&TM_bBfdi46nQ4ev68Uhq10y0A_7);
		TM_bBfdi46nQ4ev68Uhq10y0A_7.status = setjmp(TM_bBfdi46nQ4ev68Uhq10y0A_7.context);
		if (TM_bBfdi46nQ4ev68Uhq10y0A_7.status == 0) {
			tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window;
			TSafePoint TM_bBfdi46nQ4ev68Uhq10y0A_10;
			nimln_(71, "smoke.nim");
			{
				NIM_BOOL T25_;
				tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg* volatile e_3;
				NimStringDesc* T28_;
				NCSTRING T29_;
				NimStringDesc* T30_;
				T25_ = (NIM_BOOL)0;
				T25_ = Dl_148013_("SDL_RENDER_SCALE_QUALITY", "2");
				if (!!(T25_)) goto LA26_;
				e_3 = (tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg*)0;
				nimln_(2811, "system.nim");
				e_3 = (tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg*) newObj((&NTI_yEsavQFTBQGpgLZ3fCM9aPA_), sizeof(tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg));
				(*e_3).Sup.Sup.m_type = (&NTI_HEToztgn9a0zVfyFTQj1vQg_);
				nimln_(72, "smoke.nim");
				T28_ = (NimStringDesc*)0;
				nimln_(18, "smoke.nim");
				T29_ = (NCSTRING)0;
				T29_ = Dl_147654_();
				T30_ = (NimStringDesc*)0;
				T30_ = cstrToNimstr(T29_);
				T28_ = rawNewString(((NimStringDesc*) &TM_bBfdi46nQ4ev68Uhq10y0A_8)->Sup.len + T30_->Sup.len + 13);
appendString(T28_, ((NimStringDesc*) &TM_bBfdi46nQ4ev68Uhq10y0A_8));
appendString(T28_, ((NimStringDesc*) &TM_bBfdi46nQ4ev68Uhq10y0A_4));
appendString(T28_, T30_);
				asgnRefNoCycle((void**) (&(*e_3).Sup.message), T28_);
				nimln_(2806, "system.nim");
				asgnRef((void**) (&(*e_3).Sup.parent), NIM_NIL);
				nimln_(17, "smoke.nim");
				raiseException((Exception*)e_3, "SDLException");
			}
			LA26_: ;
			nimln_(74, "smoke.nim");
			window = Dl_147356_("Smoke", ((int) 805240832), ((int) 805240832), ((int) 1280), ((int) 720), ((unsigned int) 4));
			nimln_(77, "smoke.nim");
			{
				tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg* volatile e_4;
				NimStringDesc* T35_;
				NCSTRING T36_;
				NimStringDesc* T37_;
				if (!(window == 0)) goto LA33_;
				e_4 = (tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg*)0;
				nimln_(2811, "system.nim");
				e_4 = (tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg*) newObj((&NTI_yEsavQFTBQGpgLZ3fCM9aPA_), sizeof(tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg));
				(*e_4).Sup.Sup.m_type = (&NTI_HEToztgn9a0zVfyFTQj1vQg_);
				nimln_(77, "smoke.nim");
				T35_ = (NimStringDesc*)0;
				nimln_(18, "smoke.nim");
				T36_ = (NCSTRING)0;
				T36_ = Dl_147654_();
				T37_ = (NimStringDesc*)0;
				T37_ = cstrToNimstr(T36_);
				T35_ = rawNewString(((NimStringDesc*) &TM_bBfdi46nQ4ev68Uhq10y0A_9)->Sup.len + T37_->Sup.len + 13);
appendString(T35_, ((NimStringDesc*) &TM_bBfdi46nQ4ev68Uhq10y0A_9));
appendString(T35_, ((NimStringDesc*) &TM_bBfdi46nQ4ev68Uhq10y0A_4));
appendString(T35_, T37_);
				asgnRefNoCycle((void**) (&(*e_4).Sup.message), T35_);
				nimln_(2806, "system.nim");
				asgnRef((void**) (&(*e_4).Sup.parent), NIM_NIL);
				nimln_(17, "smoke.nim");
				raiseException((Exception*)e_4, "SDLException");
			}
			LA33_: ;
			nimln_(78, "smoke.nim");
			pushSafePoint(&TM_bBfdi46nQ4ev68Uhq10y0A_10);
			TM_bBfdi46nQ4ev68Uhq10y0A_10.status = setjmp(TM_bBfdi46nQ4ev68Uhq10y0A_10.context);
			if (TM_bBfdi46nQ4ev68Uhq10y0A_10.status == 0) {
				tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer;
				TSafePoint TM_bBfdi46nQ4ev68Uhq10y0A_12;
				nimln_(80, "smoke.nim");
				renderer = Dl_146811_(window, ((int) -1), ((NI32) 6));
				nimln_(82, "smoke.nim");
				{
					tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg* volatile e_5;
					NimStringDesc* T43_;
					NCSTRING T44_;
					NimStringDesc* T45_;
					if (!(renderer == 0)) goto LA41_;
					e_5 = (tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg*)0;
					nimln_(2811, "system.nim");
					e_5 = (tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg*) newObj((&NTI_yEsavQFTBQGpgLZ3fCM9aPA_), sizeof(tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg));
					(*e_5).Sup.Sup.m_type = (&NTI_HEToztgn9a0zVfyFTQj1vQg_);
					nimln_(82, "smoke.nim");
					T43_ = (NimStringDesc*)0;
					nimln_(18, "smoke.nim");
					T44_ = (NCSTRING)0;
					T44_ = Dl_147654_();
					T45_ = (NimStringDesc*)0;
					T45_ = cstrToNimstr(T44_);
					T43_ = rawNewString(((NimStringDesc*) &TM_bBfdi46nQ4ev68Uhq10y0A_11)->Sup.len + T45_->Sup.len + 13);
appendString(T43_, ((NimStringDesc*) &TM_bBfdi46nQ4ev68Uhq10y0A_11));
appendString(T43_, ((NimStringDesc*) &TM_bBfdi46nQ4ev68Uhq10y0A_4));
appendString(T43_, T45_);
					asgnRefNoCycle((void**) (&(*e_5).Sup.message), T43_);
					nimln_(2806, "system.nim");
					asgnRef((void**) (&(*e_5).Sup.parent), NIM_NIL);
					nimln_(17, "smoke.nim");
					raiseException((Exception*)e_5, "SDLException");
				}
				LA41_: ;
				nimln_(83, "smoke.nim");
				pushSafePoint(&TM_bBfdi46nQ4ev68Uhq10y0A_12);
				TM_bBfdi46nQ4ev68Uhq10y0A_12.status = setjmp(TM_bBfdi46nQ4ev68Uhq10y0A_12.context);
				if (TM_bBfdi46nQ4ev68Uhq10y0A_12.status == 0) {
					tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw T47_;
					tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA* game;
					NF volatile lastTime;
					nimln_(86, "smoke.nim");
					T47_ = (tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw)0;
					T47_ = Dl_146617_(renderer, ((NU8) 110), ((NU8) 132), ((NU8) 174), ((NU8) 255));
					nimln_(88, "smoke.nim");
					{
						int T50_;
						T50_ = (int)0;
						T50_ = Dl_146606_(renderer, ((int) 320), ((int) 160));
						if (!(T50_ < ((NI32) 0))) goto LA51_;
						nimln_(89, "smoke.nim");
						echoBinSafe(TM_bBfdi46nQ4ev68Uhq10y0A_13, 1);
					}
					LA51_: ;
					nimln_(90, "smoke.nim");
					{
						NIM_BOOL T55_;
						nimln_(16, "render.nim");
						T55_ = (NIM_BOOL)0;
						T55_ = Dl_148013_("SDL_RENDER_SCALE_QUALITY", "0");
						if (!!(T55_)) goto LA56_;
						nimln_(91, "smoke.nim");
						echoBinSafe(TM_bBfdi46nQ4ev68Uhq10y0A_15, 1);
					}
					LA56_: ;
					nimln_(93, "smoke.nim");
					initTextures_5jhsfEp2uQLg0uKv65KfVg(renderer);
					nimln_(95, "smoke.nim");
					game = initGameData_SMOesfyeK6X3txgLgpEMOQ(renderer);
					nimln_(97, "smoke.nim");
					lastTime = ntepochTime();
					{
						nimln_(99, "smoke.nim");
						while (1) {
							NF now;
							NF dt;
							if (!!((*game).inputs[(((tyEnum_Input_HkmkensvbmBMoEqXX3PFKw) 5))- 0])) goto LA59;
							nimln_(100, "smoke.nim");
							now = ntepochTime();
							nimln_(101, "smoke.nim");
							dt = ((NF)(now) - (NF)(lastTime));
							nimln_(102, "smoke.nim");
							lastTime = now;
							nimln_(103, "smoke.nim");
							handleInput_4cFc3ApldCyqXVMMnn1bmQ(&game);
							nimln_(104, "smoke.nim");
							loop_Z9bGN9cEjwwM1MosnoQKTduA(&game, dt);
							nimln_(105, "smoke.nim");
							render_4cFc3ApldCyqXVMMnn1bmQ_2(&game);
						} LA59: ;
					}
					popSafePoint();
				}
				else {
					popSafePoint();
					setFrame((TFrame*)&FR_);
				}
				{
					nimln_(83, "smoke.nim");
					Dl_146648_(renderer);
				}
				if (TM_bBfdi46nQ4ev68Uhq10y0A_12.status != 0) reraiseException();
				popSafePoint();
			}
			else {
				popSafePoint();
				setFrame((TFrame*)&FR_);
			}
			{
				nimln_(78, "smoke.nim");
				destroy_sFvfWODyHxg46OuBtGyU8Qsmoke(window);
			}
			if (TM_bBfdi46nQ4ev68Uhq10y0A_10.status != 0) reraiseException();
			popSafePoint();
		}
		else {
			popSafePoint();
			setFrame((TFrame*)&FR_);
		}
		{
			nimln_(69, "smoke.nim");
			Dl_149607_();
		}
		if (TM_bBfdi46nQ4ev68Uhq10y0A_7.status != 0) reraiseException();
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR_);
	}
	{
		nimln_(64, "smoke.nim");
		Dl_146777_();
	}
	if (TM_bBfdi46nQ4ev68Uhq10y0A_5.status != 0) reraiseException();
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_macrosDatInit000();
	stdlib_unsignedDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	sdl2_sdl2DatInit000();
	sdl2_imageDatInit000();
	stdlib_dynlibDatInit000();
	stdlib_winleanDatInit000();
	stdlib_timesDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	smoke_vectorDatInit000();
	smoke_matrixDatInit000();
	stdlib_randomDatInit000();
	smoke_directionDatInit000();
	smoke_constantsDatInit000();
	smoke_utilsDatInit000();
	stdlib_hashesDatInit000();
	stdlib_tablesDatInit000();
	smoke_texturesDatInit000();
	smoke_clothingtypesDatInit000();
	smoke_characterDatInit000();
	smoke_gamestateDatInit000();
	smoke_rectangleDatInit000();
	smoke_shadowcastingDatInit000();
	smoke_renderDatInit000();
	smokeDatInit000();
	stdlib_macrosInit000();
	stdlib_unsignedInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	sdl2_sdl2Init000();
	sdl2_imageInit000();
	stdlib_dynlibInit000();
	stdlib_winleanInit000();
	stdlib_timesInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	smoke_vectorInit000();
	smoke_matrixInit000();
	stdlib_randomInit000();
	smoke_directionInit000();
	smoke_constantsInit000();
	smoke_utilsInit000();
	stdlib_hashesInit000();
	stdlib_tablesInit000();
	smoke_texturesInit000();
	smoke_clothingtypesInit000();
	smoke_characterInit000();
	smoke_gamestateInit000();
	smoke_rectangleInit000();
	smoke_shadowcastingInit000();
	smoke_renderInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("smoke", "smoke.nim");
	nimln_(107, "smoke.nim");
	main_bWnkIoWyFFnjlYj9a9baJQYw();
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, smokeDatInit000)(void) {
static TNimNode TM_bBfdi46nQ4ev68Uhq10y0A_0[1];
NTI_HEToztgn9a0zVfyFTQj1vQg_.size = sizeof(tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg);
NTI_HEToztgn9a0zVfyFTQj1vQg_.kind = 17;
NTI_HEToztgn9a0zVfyFTQj1vQg_.base = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
TM_bBfdi46nQ4ev68Uhq10y0A_0[0].len = 0; TM_bBfdi46nQ4ev68Uhq10y0A_0[0].kind = 2;
NTI_HEToztgn9a0zVfyFTQj1vQg_.node = &TM_bBfdi46nQ4ev68Uhq10y0A_0[0];
NTI_yEsavQFTBQGpgLZ3fCM9aPA_.size = sizeof(tyObject_SDLException_HEToztgn9a0zVfyFTQj1vQg*);
NTI_yEsavQFTBQGpgLZ3fCM9aPA_.kind = 22;
NTI_yEsavQFTBQGpgLZ3fCM9aPA_.base = (&NTI_HEToztgn9a0zVfyFTQj1vQg_);
NTI_yEsavQFTBQGpgLZ3fCM9aPA_.marker = Marker_tyRef_yEsavQFTBQGpgLZ3fCM9aPA;
}

