/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -I"C:\Program Files\nim\nim-0.18.0\lib" -o "C:\Users\Quinn Freedman\workspace\nim\smoke\src\nimcache\smoke_direction.o" "C:\Users\Quinn Freedman\workspace\nim\smoke\src\nimcache\smoke_direction.c" */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef NU8 tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
TNimType NTI_p7h0usAc9c3d7sTkU0MWLNg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
NIM_EXTERNC N_NOINLINE(void, smoke_directionInit000)(void) {
	nimfr_("direction", "direction.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, smoke_directionDatInit000)(void) {
static TNimNode* TM_RQRGcgnPvIYvmqCEgCbvwg_2[4];
NI TM_RQRGcgnPvIYvmqCEgCbvwg_4;
static char* NIM_CONST TM_RQRGcgnPvIYvmqCEgCbvwg_3[4] = {
"up", 
"down", 
"left", 
"right"};
static TNimNode TM_RQRGcgnPvIYvmqCEgCbvwg_0[5];
NTI_p7h0usAc9c3d7sTkU0MWLNg_.size = sizeof(tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg);
NTI_p7h0usAc9c3d7sTkU0MWLNg_.kind = 14;
NTI_p7h0usAc9c3d7sTkU0MWLNg_.base = 0;
NTI_p7h0usAc9c3d7sTkU0MWLNg_.flags = 3;
for (TM_RQRGcgnPvIYvmqCEgCbvwg_4 = 0; TM_RQRGcgnPvIYvmqCEgCbvwg_4 < 4; TM_RQRGcgnPvIYvmqCEgCbvwg_4++) {
TM_RQRGcgnPvIYvmqCEgCbvwg_0[TM_RQRGcgnPvIYvmqCEgCbvwg_4+0].kind = 1;
TM_RQRGcgnPvIYvmqCEgCbvwg_0[TM_RQRGcgnPvIYvmqCEgCbvwg_4+0].offset = TM_RQRGcgnPvIYvmqCEgCbvwg_4;
TM_RQRGcgnPvIYvmqCEgCbvwg_0[TM_RQRGcgnPvIYvmqCEgCbvwg_4+0].name = TM_RQRGcgnPvIYvmqCEgCbvwg_3[TM_RQRGcgnPvIYvmqCEgCbvwg_4];
TM_RQRGcgnPvIYvmqCEgCbvwg_2[TM_RQRGcgnPvIYvmqCEgCbvwg_4] = &TM_RQRGcgnPvIYvmqCEgCbvwg_0[TM_RQRGcgnPvIYvmqCEgCbvwg_4+0];
}
TM_RQRGcgnPvIYvmqCEgCbvwg_0[4].len = 4; TM_RQRGcgnPvIYvmqCEgCbvwg_0[4].kind = 2; TM_RQRGcgnPvIYvmqCEgCbvwg_0[4].sons = &TM_RQRGcgnPvIYvmqCEgCbvwg_2[0];
NTI_p7h0usAc9c3d7sTkU0MWLNg_.node = &TM_RQRGcgnPvIYvmqCEgCbvwg_0[4];
}

