/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -I"C:\Program Files\nim\nim-0.18.0\lib" -o "C:\Users\Quinn Freedman\workspace\nim\smoke\src\nimcache\smoke_gamestate.o" "C:\Users\Quinn Freedman\workspace\nim\smoke\src\nimcache\smoke_gamestate.c" */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Rand_liBKmwv1H6v7oYBhDFHa6A tyObject_Rand_liBKmwv1H6v7oYBhDFHa6A;
typedef struct tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ;
typedef struct tyObject_Matrix_5jfXleRjKMzj7p29cba2i9bg tyObject_Matrix_5jfXleRjKMzj7p29cba2i9bg;
typedef struct tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g;
typedef struct tySequence_6MHxSSkCYafnfGYzxyCqtA tySequence_6MHxSSkCYafnfGYzxyCqtA;
typedef struct tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw;
typedef struct tySequence_shxop0zPIs5Ec3k71aCLuQ tySequence_shxop0zPIs5Ec3k71aCLuQ;
typedef struct tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg;
typedef struct tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA;
typedef struct tyObject_ItemSet_q6qi9bPVWXyspg9bTRkyuyXw tyObject_ItemSet_q6qi9bPVWXyspg9bTRkyuyXw;
typedef struct tyObject_ClothingHead_h3YfKnLVYVYocWj5dIBPGw tyObject_ClothingHead_h3YfKnLVYVYocWj5dIBPGw;
typedef struct tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_ClothingBody_jYCMVvD4caXGho8aDSyHJQ tyObject_ClothingBody_jYCMVvD4caXGho8aDSyHJQ;
typedef struct tyObject_ClothingFeet_UGmkgjwjxmZBaRBpyJpGvw tyObject_ClothingFeet_UGmkgjwjxmZBaRBpyJpGvw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ;
typedef struct tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA;
typedef struct tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg;
struct tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g {
NI x;
NI y;
};
struct tyObject_Matrix_5jfXleRjKMzj7p29cba2i9bg {
NI width;
NI height;
tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g offset;
tySequence_6MHxSSkCYafnfGYzxyCqtA* data;
};
struct tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw {
NI width;
NI height;
tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g offset;
tySequence_shxop0zPIs5Ec3k71aCLuQ* data;
};
struct tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA {
NF x;
NF y;
};
typedef NU8 tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg;
typedef NU8 tyEnum_Race_wN6IdQU5M5xJLM35A76jlQ;
typedef NU8 tyEnum_Sex_fZXzEuE89cG49aK9cXfwfCxeQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg {
NimStringDesc* name;
};
struct tyObject_ClothingHead_h3YfKnLVYVYocWj5dIBPGw {
tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg stats;
};
struct tyObject_ClothingBody_jYCMVvD4caXGho8aDSyHJQ {
tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg stats;
};
struct tyObject_ClothingFeet_UGmkgjwjxmZBaRBpyJpGvw {
tyObject_ClothingStats_zxet1nto49a9ae8pLlAU14cg stats;
};
struct tyObject_ItemSet_q6qi9bPVWXyspg9bTRkyuyXw {
tyObject_ClothingHead_h3YfKnLVYVYocWj5dIBPGw head;
tyObject_ClothingBody_jYCMVvD4caXGho8aDSyHJQ body;
tyObject_ClothingFeet_UGmkgjwjxmZBaRBpyJpGvw legs;
};
typedef NU8 tyEnum_TextureAlias_6sotYNRMaoTgzBzqkJyyLQ;
struct tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg {
tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g currentTile;
tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g nextTile;
tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA actualPos;
tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg facing;
NF speed;
tyEnum_Race_wN6IdQU5M5xJLM35A76jlQ race;
tyEnum_Sex_fZXzEuE89cG49aK9cXfwfCxeQ sex;
tyObject_ItemSet_q6qi9bPVWXyspg9bTRkyuyXw items;
tyEnum_TextureAlias_6sotYNRMaoTgzBzqkJyyLQ spritesheet;
};
struct tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ {
tyObject_Matrix_5jfXleRjKMzj7p29cba2i9bg mapTextures;
tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw walls;
tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg playerCharacter;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ {
int Field0;
int Field1;
int Field2;
int Field3;
};
typedef NIM_BOOL tyArray_k64wcrcoLEGgK5bVTvG2WA[6];
struct tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA {
tyArray_k64wcrcoLEGgK5bVTvG2WA inputs;
tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer;
tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ gameState;
};
struct tyObject_Rand_liBKmwv1H6v7oYBhDFHa6A {
NU64 a0;
NU64 a1;
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
typedef NU8 tyEnum_Input_HkmkensvbmBMoEqXX3PFKw;
struct tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg {
char dummy;
};
struct tySequence_6MHxSSkCYafnfGYzxyCqtA {
  TGenericSeq Sup;
  tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ data[SEQ_DECL_SIZE];
};
struct tySequence_shxop0zPIs5Ec3k71aCLuQ {
  TGenericSeq Sup;
  NIM_BOOL data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, initGamestate_CFfqqdbrZ0dWsyve4jYUEw)(tyObject_Rand_liBKmwv1H6v7oYBhDFHa6A* rng, tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(void, newCharacter_Ia3w0EG3EIpjyMYcAfcqRA)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g pos, NF speed, tyEnum_Race_wN6IdQU5M5xJLM35A76jlQ race, tyEnum_Sex_fZXzEuE89cG49aK9cXfwfCxeQ sex, tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg* Result);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g, v_g7Ok4O0iyLEmW9bny8ZknmA)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(void, newMatrix_M0SbTQ7CK3cgtJ3Pxb1eRg)(NI width, NI height, tyObject_Matrix_5jfXleRjKMzj7p29cba2i9bg* Result);
N_LIB_PRIVATE N_NIMCALL(void, newMatrix_WRyqL4rA9c9b9ckAdQys1qMYA)(NI width, NI height, tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw* Result);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, divInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NI, rand_f9cZ4wTU5lMiIukSmr9btSpg)(tyObject_Rand_liBKmwv1H6v7oYBhDFHa6A* r, NI max);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(void, X5BX5Deq__MRT9ab6WYeII9bJwD1RzkmJQgamestate)(tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw* self, NI x, NI y, NIM_BOOL value);
N_LIB_PRIVATE N_NIMCALL(void, set_dwKTQMqun8vrCrUIi6jcSg)(tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw* self, NI x, NI y, NIM_BOOL value);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, X5BX5Deq__CTWWOA0IBuFkbPLjBL0nKQgamestate)(tyObject_Matrix_5jfXleRjKMzj7p29cba2i9bg* self, NI x, NI y, tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ value);
N_LIB_PRIVATE N_NIMCALL(void, set_8NMCqEAEsAGwEgYC813byQ)(tyObject_Matrix_5jfXleRjKMzj7p29cba2i9bg* self, NI x, NI y, tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ value);
N_LIB_PRIVATE N_NIMCALL(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA*, initGameData_SMOesfyeK6X3txgLgpEMOQ)(tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_lJGwzzOtEj8PUQVSnppB6w)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(NF, ntepochTime)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_Rand_liBKmwv1H6v7oYBhDFHa6A, initRand_NhNuJ1iY3C86G3dMQp4bRg)(NI64 seed);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatVarargs)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen_0);
N_NIMCALL(NimStringDesc*, nimInt64ToStr)(NI64 x);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, loop_Z9bGN9cEjwwM1MosnoQKTduA)(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA** self, NF dt);
N_LIB_PRIVATE N_NIMCALL(void, move_9aRX7iIU7VSOII1UqhN8edQ)(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg* self, tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg dir, tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw* collision);
N_LIB_PRIVATE N_NIMCALL(void, update_pBfJunJAWPEnvkt2lnqkcA)(tyObject_Character_z7sEl7rGLIEtgyeCSL9aOwg* self, NF dt);
N_LIB_PRIVATE N_NIMCALL(tySequence_6MHxSSkCYafnfGYzxyCqtA*, newSeq_Vwp4M09ciGpSzWSD1pqtZ6w)(NI len);
N_LIB_PRIVATE N_NIMCALL(tySequence_shxop0zPIs5Ec3k71aCLuQ*, newSeq_Ltn5D7x7AgJUEN0OQVkiEw)(NI len);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__BNdGsTV6ZFhDHZTIzaJY5Q)(tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw* self);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__QlLPjMfIso9bq08SGs3fS7g)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted_nyaZAljVI03SH2d9cnD0WMw)(NimStringDesc** s, NI x);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__hvNTR4uxZJu8fvePwaextw)(tyObject_Matrix_5jfXleRjKMzj7p29cba2i9bg* self);
TNimType NTI_np3Rx8N215Y1kfBowS8mPQ_;
extern TNimType NTI_5jfXleRjKMzj7p29cba2i9bg_;
extern TNimType NTI_Uogfi9b3606EsxiEmiGDiAw_;
extern TNimType NTI_z7sEl7rGLIEtgyeCSL9aOwg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_CtGi8Xr9b12gKxEZURFqedA_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
TNimType NTI_k64wcrcoLEGgK5bVTvG2WA_;
extern TNimType NTI_7lSakCSU4VtJLR9aqvUx9buA_;
TNimType NTI_lJGwzzOtEj8PUQVSnppB6w_;
NIM_CONST tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ TM_Q01Ygr8gIHg9bmY3vO9anPCQ_8 = {((int) 0),
((int) 64),
((int) 32),
((int) 32)}
;
NIM_CONST tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ TM_Q01Ygr8gIHg9bmY3vO9anPCQ_9 = {((int) 224),
((int) 32),
((int) 32),
((int) 32)}
;
STRING_LITERAL(TM_Q01Ygr8gIHg9bmY3vO9anPCQ_12, "Creating map with seed: $1", 26);

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	result = (NI)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(void, X5BX5Deq__MRT9ab6WYeII9bJwD1RzkmJQgamestate)(tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw* self, NI x, NI y, NIM_BOOL value) {
	nimfr_("[]=", "matrix.nim");
	nimln_(62, "matrix.nim");
	set_dwKTQMqun8vrCrUIi6jcSg(self, x, y, value);
	popFrame();
}

static N_INLINE(void, X5BX5Deq__CTWWOA0IBuFkbPLjBL0nKQgamestate)(tyObject_Matrix_5jfXleRjKMzj7p29cba2i9bg* self, NI x, NI y, tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ value) {
	nimfr_("[]=", "matrix.nim");
	nimln_(62, "matrix.nim");
	set_8NMCqEAEsAGwEgYC813byQ(self, x, y, value);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, initGamestate_CFfqqdbrZ0dWsyve4jYUEw)(tyObject_Rand_liBKmwv1H6v7oYBhDFHa6A* rng, tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ* Result) {
	tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g T1_;
	NI levelWidth;
	NI levelHeight;
	nimfr_("initGamestate", "gamestate.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_np3Rx8N215Y1kfBowS8mPQ_));
	nimln_(28, "gamestate.nim");
	T1_ = v_g7Ok4O0iyLEmW9bny8ZknmA(((NI) 0), ((NI) 0));
	newCharacter_Ia3w0EG3EIpjyMYcAfcqRA(T1_, 1.5000000000000000e+000, ((tyEnum_Race_wN6IdQU5M5xJLM35A76jlQ) 0), ((tyEnum_Sex_fZXzEuE89cG49aK9cXfwfCxeQ) 0), (&(*Result).playerCharacter));
	nimln_(29, "gamestate.nim");
	levelWidth = ((NI) 10);
	nimln_(30, "gamestate.nim");
	levelHeight = ((NI) 10);
	nimln_(31, "gamestate.nim");
	newMatrix_M0SbTQ7CK3cgtJ3Pxb1eRg(levelWidth, levelHeight, (&(*Result).mapTextures));
	nimln_(32, "gamestate.nim");
	newMatrix_WRyqL4rA9c9b9ckAdQys1qMYA(levelWidth, levelHeight, (&(*Result).walls));
	{
		NI x;
		NI y;
		tyObject_Matrix_Uogfi9b3606EsxiEmiGDiAw colontmp_;
		NI width;
		NI height;
		x = (NI)0;
		y = (NI)0;
		memset((void*)(&colontmp_), 0, sizeof(colontmp_));
		nimln_(33, "gamestate.nim");
		colontmp_.width = (*Result).walls.width;
		colontmp_.height = (*Result).walls.height;
		colontmp_.offset = (*Result).walls.offset;
		colontmp_.data = (*Result).walls.data;
		nimln_(78, "matrix.nim");
		width = colontmp_.width;
		nimln_(79, "matrix.nim");
		height = colontmp_.height;
		{
			NI i;
			NI colontmp__2;
			NI TM_Q01Ygr8gIHg9bmY3vO9anPCQ_3;
			NI i_2;
			i = (NI)0;
			colontmp__2 = (NI)0;
			nimln_(80, "matrix.nim");
			TM_Q01Ygr8gIHg9bmY3vO9anPCQ_3 = mulInt(width, height);
			colontmp__2 = (NI)(TM_Q01Ygr8gIHg9bmY3vO9anPCQ_3);
			nimln_(3519, "system.nim");
			i_2 = ((NI) 0);
			{
				nimln_(3520, "system.nim");
				while (1) {
					NI x_2;
					NI TM_Q01Ygr8gIHg9bmY3vO9anPCQ_4;
					NI TM_Q01Ygr8gIHg9bmY3vO9anPCQ_5;
					NI y_2;
					NI TM_Q01Ygr8gIHg9bmY3vO9anPCQ_6;
					NI TM_Q01Ygr8gIHg9bmY3vO9anPCQ_7;
					NI TM_Q01Ygr8gIHg9bmY3vO9anPCQ_10;
					if (!(i_2 < colontmp__2)) goto LA5;
					nimln_(3521, "system.nim");
					i = i_2;
					nimln_(81, "matrix.nim");
					TM_Q01Ygr8gIHg9bmY3vO9anPCQ_4 = modInt(i, width);
					TM_Q01Ygr8gIHg9bmY3vO9anPCQ_5 = addInt((NI)(TM_Q01Ygr8gIHg9bmY3vO9anPCQ_4), colontmp_.offset.x);
					x_2 = (NI)(TM_Q01Ygr8gIHg9bmY3vO9anPCQ_5);
					nimln_(82, "matrix.nim");
					TM_Q01Ygr8gIHg9bmY3vO9anPCQ_6 = divInt(i, width);
					TM_Q01Ygr8gIHg9bmY3vO9anPCQ_7 = addInt((NI)(TM_Q01Ygr8gIHg9bmY3vO9anPCQ_6), colontmp_.offset.y);
					y_2 = (NI)(TM_Q01Ygr8gIHg9bmY3vO9anPCQ_7);
					nimln_(83, "matrix.nim");
					x = x_2;
					y = y_2;
					nimln_(34, "gamestate.nim");
					{
						NI T8_;
						T8_ = (NI)0;
						T8_ = rand_f9cZ4wTU5lMiIukSmr9btSpg(rng, ((NI) 1));
						if (!((NIM_BOOL)chckRange(T8_, NIM_FALSE, NIM_TRUE))) goto LA9_;
						nimln_(35, "gamestate.nim");
						X5BX5Deq__MRT9ab6WYeII9bJwD1RzkmJQgamestate((&(*Result).walls), x, y, NIM_TRUE);
						nimln_(36, "gamestate.nim");
						X5BX5Deq__CTWWOA0IBuFkbPLjBL0nKQgamestate((&(*Result).mapTextures), x, y, TM_Q01Ygr8gIHg9bmY3vO9anPCQ_8);
					}
					goto LA6_;
					LA9_: ;
					{
						nimln_(38, "gamestate.nim");
						X5BX5Deq__CTWWOA0IBuFkbPLjBL0nKQgamestate((&(*Result).mapTextures), x, y, TM_Q01Ygr8gIHg9bmY3vO9anPCQ_9);
					}
					LA6_: ;
					nimln_(3522, "system.nim");
					TM_Q01Ygr8gIHg9bmY3vO9anPCQ_10 = addInt(i_2, ((NI) 1));
					i_2 = (NI)(TM_Q01Ygr8gIHg9bmY3vO9anPCQ_10);
				} LA5: ;
			}
		}
	}
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_lJGwzzOtEj8PUQVSnppB6w)(void* p, NI op) {
	tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA* a;
	NI T1_;
	a = (tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA*)p;
	T1_ = (NI)0;
	nimGCvisit((void*)(*a).gameState.mapTextures.data, op);
	nimGCvisit((void*)(*a).gameState.walls.data, op);
	nimGCvisit((void*)(*a).gameState.playerCharacter.items.head.stats.name, op);
	nimGCvisit((void*)(*a).gameState.playerCharacter.items.body.stats.name, op);
	nimGCvisit((void*)(*a).gameState.playerCharacter.items.legs.stats.name, op);
}

N_LIB_PRIVATE N_NIMCALL(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA*, initGameData_SMOesfyeK6X3txgLgpEMOQ)(tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer) {
	tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA* result;
	NI64 seed;
	NF T1_;
	tyObject_Rand_liBKmwv1H6v7oYBhDFHa6A rng;
	tyArray_nHXaesL0DJZHyVS07ARPRA T2_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T3_;
	nimfr_("initGameData", "gamestate.nim");
	result = (tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA*)0;
	nimln_(42, "gamestate.nim");
	result = (tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA*) newObj((&NTI_lJGwzzOtEj8PUQVSnppB6w_), sizeof(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA));
	nimln_(43, "gamestate.nim");
	(*result).renderer = renderer;
	nimln_(44, "gamestate.nim");
	T1_ = (NF)0;
	T1_ = ntepochTime();
	seed = ((NI64) (T1_));
	nimln_(45, "gamestate.nim");
	rng = initRand_NhNuJ1iY3C86G3dMQp4bRg(seed);
	nimln_(46, "gamestate.nim");
	memset((void*)T2_, 0, sizeof(T2_));
	memset((void*)T3_, 0, sizeof(T3_));
	T3_[0] = nimInt64ToStr(seed);
	T2_[0] = nsuFormatVarargs(((NimStringDesc*) &TM_Q01Ygr8gIHg9bmY3vO9anPCQ_12), T3_, 1);
	echoBinSafe(T2_, 1);
	nimln_(47, "gamestate.nim");
	initGamestate_CFfqqdbrZ0dWsyve4jYUEw((&rng), (&(*result).gameState));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, loop_Z9bGN9cEjwwM1MosnoQKTduA)(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA** self, NF dt) {
	nimfr_("loop", "gamestate.nim");
	nimln_(51, "gamestate.nim");
	{
		if (!(*(*self)).inputs[(((tyEnum_Input_HkmkensvbmBMoEqXX3PFKw) 3))- 0]) goto LA3_;
		nimln_(52, "gamestate.nim");
		move_9aRX7iIU7VSOII1UqhN8edQ((&(*(*self)).gameState.playerCharacter), ((tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg) 0), (&(*(*self)).gameState.walls));
	}
	LA3_: ;
	nimln_(54, "gamestate.nim");
	{
		if (!(*(*self)).inputs[(((tyEnum_Input_HkmkensvbmBMoEqXX3PFKw) 4))- 0]) goto LA7_;
		nimln_(55, "gamestate.nim");
		move_9aRX7iIU7VSOII1UqhN8edQ((&(*(*self)).gameState.playerCharacter), ((tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg) 1), (&(*(*self)).gameState.walls));
	}
	LA7_: ;
	nimln_(57, "gamestate.nim");
	{
		if (!(*(*self)).inputs[(((tyEnum_Input_HkmkensvbmBMoEqXX3PFKw) 1))- 0]) goto LA11_;
		nimln_(58, "gamestate.nim");
		move_9aRX7iIU7VSOII1UqhN8edQ((&(*(*self)).gameState.playerCharacter), ((tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg) 2), (&(*(*self)).gameState.walls));
	}
	LA11_: ;
	nimln_(60, "gamestate.nim");
	{
		if (!(*(*self)).inputs[(((tyEnum_Input_HkmkensvbmBMoEqXX3PFKw) 2))- 0]) goto LA15_;
		nimln_(61, "gamestate.nim");
		move_9aRX7iIU7VSOII1UqhN8edQ((&(*(*self)).gameState.playerCharacter), ((tyEnum_Direction_p7h0usAc9c3d7sTkU0MWLNg) 3), (&(*(*self)).gameState.walls));
	}
	LA15_: ;
	nimln_(64, "gamestate.nim");
	update_pBfJunJAWPEnvkt2lnqkcA((&(*(*self)).gameState.playerCharacter), dt);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, smoke_gamestateInit000)(void) {
	nimfr_("gamestate", "gamestate.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, smoke_gamestateDatInit000)(void) {
static TNimNode* TM_Q01Ygr8gIHg9bmY3vO9anPCQ_2[3];
static TNimNode* TM_Q01Ygr8gIHg9bmY3vO9anPCQ_11[3];
static TNimNode TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[8];
NTI_np3Rx8N215Y1kfBowS8mPQ_.size = sizeof(tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ);
NTI_np3Rx8N215Y1kfBowS8mPQ_.kind = 18;
NTI_np3Rx8N215Y1kfBowS8mPQ_.base = 0;
NTI_np3Rx8N215Y1kfBowS8mPQ_.flags = 2;
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_2[0] = &TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[1];
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[1].kind = 1;
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[1].offset = offsetof(tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ, mapTextures);
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[1].typ = (&NTI_5jfXleRjKMzj7p29cba2i9bg_);
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[1].name = "mapTextures";
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_2[1] = &TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[2];
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[2].kind = 1;
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[2].offset = offsetof(tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ, walls);
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[2].typ = (&NTI_Uogfi9b3606EsxiEmiGDiAw_);
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[2].name = "walls";
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_2[2] = &TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[3];
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[3].kind = 1;
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[3].offset = offsetof(tyObject_GameState_np3Rx8N215Y1kfBowS8mPQ, playerCharacter);
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[3].typ = (&NTI_z7sEl7rGLIEtgyeCSL9aOwg_);
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[3].name = "playerCharacter";
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[0].len = 3; TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[0].kind = 2; TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[0].sons = &TM_Q01Ygr8gIHg9bmY3vO9anPCQ_2[0];
NTI_np3Rx8N215Y1kfBowS8mPQ_.node = &TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[0];
NTI_CtGi8Xr9b12gKxEZURFqedA_.size = sizeof(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA);
NTI_CtGi8Xr9b12gKxEZURFqedA_.kind = 18;
NTI_CtGi8Xr9b12gKxEZURFqedA_.base = 0;
NTI_CtGi8Xr9b12gKxEZURFqedA_.flags = 2;
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_11[0] = &TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[5];
NTI_k64wcrcoLEGgK5bVTvG2WA_.size = sizeof(tyArray_k64wcrcoLEGgK5bVTvG2WA);
NTI_k64wcrcoLEGgK5bVTvG2WA_.kind = 16;
NTI_k64wcrcoLEGgK5bVTvG2WA_.base = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
NTI_k64wcrcoLEGgK5bVTvG2WA_.flags = 3;
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[5].kind = 1;
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[5].offset = offsetof(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA, inputs);
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[5].typ = (&NTI_k64wcrcoLEGgK5bVTvG2WA_);
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[5].name = "inputs";
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_11[1] = &TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[6];
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[6].kind = 1;
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[6].offset = offsetof(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA, renderer);
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[6].typ = (&NTI_7lSakCSU4VtJLR9aqvUx9buA_);
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[6].name = "renderer";
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_11[2] = &TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[7];
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[7].kind = 1;
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[7].offset = offsetof(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA, gameState);
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[7].typ = (&NTI_np3Rx8N215Y1kfBowS8mPQ_);
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[7].name = "gameState";
TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[4].len = 3; TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[4].kind = 2; TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[4].sons = &TM_Q01Ygr8gIHg9bmY3vO9anPCQ_11[0];
NTI_CtGi8Xr9b12gKxEZURFqedA_.node = &TM_Q01Ygr8gIHg9bmY3vO9anPCQ_0[4];
NTI_lJGwzzOtEj8PUQVSnppB6w_.size = sizeof(tyObject_GamecolonObjectType__CtGi8Xr9b12gKxEZURFqedA*);
NTI_lJGwzzOtEj8PUQVSnppB6w_.kind = 22;
NTI_lJGwzzOtEj8PUQVSnppB6w_.base = (&NTI_CtGi8Xr9b12gKxEZURFqedA_);
NTI_lJGwzzOtEj8PUQVSnppB6w_.flags = 2;
NTI_lJGwzzOtEj8PUQVSnppB6w_.marker = Marker_tyRef_lJGwzzOtEj8PUQVSnppB6w;
}

