/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -I"C:\Program Files\nim\nim-0.18.0\lib" -o "C:\Users\Quinn Freedman\workspace\nim\smoke\src\nimcache\smoke_vector.o" "C:\Users\Quinn Freedman\workspace\nim\smoke\src\nimcache\smoke_vector.c" */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g;
typedef struct tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g {
NI x;
NI y;
};
struct tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA {
NF x;
NF y;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g, v_g7Ok4O0iyLEmW9bny8ZknmA)(NI x, NI y);
N_NOINLINE(void, chckNil)(void* p);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g, plus__tYFBZAVkxpPzZkVM8ktKlQ)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g self, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g other);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, pluseq__nt8lzfAY8lk9aeXOHciJ8wQ)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g* self, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g other);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g, minus__tYFBZAVkxpPzZkVM8ktKlQ_2)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g self, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g other);
static N_INLINE(NI, subInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(void, minuseq__nt8lzfAY8lk9aeXOHciJ8wQ_2)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g* self, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g other);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq__3sx5tMT4Qxpu49b019b2MQFA)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g self, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g other);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA, scale_vVZyqPj5Sma9aqMZj44YISQ)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g self, NF scale);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g, round_72NOoUEUAbMkgMXdlzTzPQ)(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA self);
N_LIB_PRIVATE N_NIMCALL(NF, round_FL9bhksfuQsfLDCxRHuknsg)(NF x, NI places);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA, plus__HfcuY0Uh67I09aLMQeXgCMQ)(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA self, tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA other);
N_LIB_PRIVATE N_NIMCALL(void, pluseq__P0YOJINg4yIpvEv0CZcShg)(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA* self, tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA other);
static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils)(NF* x, NF y);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA, minus__HfcuY0Uh67I09aLMQeXgCMQ_2)(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA self, tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA other);
N_LIB_PRIVATE N_NIMCALL(void, minuseq__P0YOJINg4yIpvEv0CZcShg_2)(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA* self, tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA other);
static N_INLINE(void, minuseq__7kHiltrvRlcg6wSYR3CxAwvector)(NF* x, NF y);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq__j9aimMR09cVUKxIDxdyeLe2A)(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA self, tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA other);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA, vecFloat_slaoZkxkeu9bF9bXg9c7JCXqQ)(NF x, NF y);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA, vecFloat_wLBMIso0HfVHu8Xdofrefw)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g v);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_7SQP9azfryP3zjoOAafzI6g_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_St31Lu7mm4aIQTpxOCjvHA_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g, v_g7Ok4O0iyLEmW9bny8ZknmA)(NI x, NI y) {
	tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g result;
	nimfr_("v", "vector.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(23, "vector.nim");
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	result.x = x;
	result.y = y;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g, plus__tYFBZAVkxpPzZkVM8ktKlQ)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g self, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g other) {
	tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g result;
	NI TM_aRNuFx1a6ph1klK2GOPKXg_2;
	NI TM_aRNuFx1a6ph1klK2GOPKXg_3;
	nimfr_("+", "vector.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(26, "vector.nim");
	TM_aRNuFx1a6ph1klK2GOPKXg_2 = addInt(self.x, other.x);
	result.x = (NI)(TM_aRNuFx1a6ph1klK2GOPKXg_2);
	nimln_(27, "vector.nim");
	TM_aRNuFx1a6ph1klK2GOPKXg_3 = addInt(self.y, other.y);
	result.y = (NI)(TM_aRNuFx1a6ph1klK2GOPKXg_3);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, pluseq__nt8lzfAY8lk9aeXOHciJ8wQ)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g* self, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g other) {
	NI TM_aRNuFx1a6ph1klK2GOPKXg_4;
	NI TM_aRNuFx1a6ph1klK2GOPKXg_5;
	nimfr_("+=", "vector.nim");
	nimln_(30, "vector.nim");
	TM_aRNuFx1a6ph1klK2GOPKXg_4 = addInt((*self).x, other.x);
	(*self).x = (NI)(TM_aRNuFx1a6ph1klK2GOPKXg_4);
	nimln_(31, "vector.nim");
	TM_aRNuFx1a6ph1klK2GOPKXg_5 = addInt((*self).y, other.y);
	(*self).y = (NI)(TM_aRNuFx1a6ph1klK2GOPKXg_5);
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g, minus__tYFBZAVkxpPzZkVM8ktKlQ_2)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g self, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g other) {
	tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g result;
	NI TM_aRNuFx1a6ph1klK2GOPKXg_6;
	NI TM_aRNuFx1a6ph1klK2GOPKXg_7;
	nimfr_("-", "vector.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(34, "vector.nim");
	TM_aRNuFx1a6ph1klK2GOPKXg_6 = subInt(self.x, other.x);
	result.x = (NI)(TM_aRNuFx1a6ph1klK2GOPKXg_6);
	nimln_(35, "vector.nim");
	TM_aRNuFx1a6ph1klK2GOPKXg_7 = subInt(self.y, other.y);
	result.y = (NI)(TM_aRNuFx1a6ph1klK2GOPKXg_7);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, minuseq__nt8lzfAY8lk9aeXOHciJ8wQ_2)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g* self, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g other) {
	NI TM_aRNuFx1a6ph1klK2GOPKXg_8;
	NI TM_aRNuFx1a6ph1klK2GOPKXg_9;
	nimfr_("-=", "vector.nim");
	nimln_(38, "vector.nim");
	TM_aRNuFx1a6ph1klK2GOPKXg_8 = subInt((*self).x, other.x);
	(*self).x = (NI)(TM_aRNuFx1a6ph1klK2GOPKXg_8);
	nimln_(39, "vector.nim");
	TM_aRNuFx1a6ph1klK2GOPKXg_9 = subInt((*self).y, other.y);
	(*self).y = (NI)(TM_aRNuFx1a6ph1klK2GOPKXg_9);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq__3sx5tMT4Qxpu49b019b2MQFA)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g self, tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g other) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("==", "vector.nim");
	result = (NIM_BOOL)0;
	nimln_(42, "vector.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = (self.x == other.x);
	if (!(T1_)) goto LA2_;
	T1_ = (self.y == other.y);
	LA2_: ;
	result = T1_;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA, scale_vVZyqPj5Sma9aqMZj44YISQ)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g self, NF scale) {
	tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA result;
	nimfr_("scale", "vector.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(49, "vector.nim");
	result.x = ((NF)(((NF) (self.x))) * (NF)(scale));
	nimln_(50, "vector.nim");
	result.y = ((NF)(((NF) (self.y))) * (NF)(scale));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g, round_72NOoUEUAbMkgMXdlzTzPQ)(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA self) {
	tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g result;
	NF T1_;
	NF T2_;
	nimfr_("round", "vector.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(53, "vector.nim");
	T1_ = (NF)0;
	T1_ = round_FL9bhksfuQsfLDCxRHuknsg(self.x, ((NI) 0));
	result.x = ((NI) (T1_));
	nimln_(54, "vector.nim");
	T2_ = (NF)0;
	T2_ = round_FL9bhksfuQsfLDCxRHuknsg(self.y, ((NI) 0));
	result.y = ((NI) (T2_));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA, plus__HfcuY0Uh67I09aLMQeXgCMQ)(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA self, tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA other) {
	tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA result;
	nimfr_("+", "vector.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(57, "vector.nim");
	result.x = ((NF)(self.x) + (NF)(other.x));
	nimln_(58, "vector.nim");
	result.y = ((NF)(self.y) + (NF)(other.y));
	popFrame();
	return result;
}

static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils)(NF* x, NF y) {
	nimfr_("+=", "system.nim");
	nimln_(3700, "system.nim");
	(*x) = ((NF)((*x)) + (NF)(y));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, pluseq__P0YOJINg4yIpvEv0CZcShg)(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA* self, tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA other) {
	nimfr_("+=", "vector.nim");
	nimln_(61, "vector.nim");
	pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&(*self).x), other.x);
	nimln_(62, "vector.nim");
	pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&(*self).y), other.y);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA, minus__HfcuY0Uh67I09aLMQeXgCMQ_2)(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA self, tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA other) {
	tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA result;
	nimfr_("-", "vector.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(65, "vector.nim");
	result.x = ((NF)(self.x) - (NF)(other.x));
	nimln_(66, "vector.nim");
	result.y = ((NF)(self.y) - (NF)(other.y));
	popFrame();
	return result;
}

static N_INLINE(void, minuseq__7kHiltrvRlcg6wSYR3CxAwvector)(NF* x, NF y) {
	nimfr_("-=", "system.nim");
	nimln_(3705, "system.nim");
	(*x) = ((NF)((*x)) - (NF)(y));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, minuseq__P0YOJINg4yIpvEv0CZcShg_2)(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA* self, tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA other) {
	nimfr_("-=", "vector.nim");
	nimln_(69, "vector.nim");
	minuseq__7kHiltrvRlcg6wSYR3CxAwvector((&(*self).x), other.x);
	nimln_(70, "vector.nim");
	minuseq__7kHiltrvRlcg6wSYR3CxAwvector((&(*self).y), other.y);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq__j9aimMR09cVUKxIDxdyeLe2A)(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA self, tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA other) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("==", "vector.nim");
	result = (NIM_BOOL)0;
	nimln_(73, "vector.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = (self.x == other.x);
	if (!(T1_)) goto LA2_;
	T1_ = (self.y == other.y);
	LA2_: ;
	result = T1_;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA, vecFloat_slaoZkxkeu9bF9bXg9c7JCXqQ)(NF x, NF y) {
	tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA result;
	nimfr_("vecFloat", "vector.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(76, "vector.nim");
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	result.x = x;
	result.y = y;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA, vecFloat_wLBMIso0HfVHu8Xdofrefw)(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g v) {
	tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA result;
	nimfr_("vecFloat", "vector.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(79, "vector.nim");
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	result.x = ((NF) (v.x));
	result.y = ((NF) (v.y));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, smoke_vectorInit000)(void) {
	nimfr_("vector", "vector.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, smoke_vectorDatInit000)(void) {
static TNimNode* TM_aRNuFx1a6ph1klK2GOPKXg_10[2];
static TNimNode* TM_aRNuFx1a6ph1klK2GOPKXg_11[2];
static TNimNode TM_aRNuFx1a6ph1klK2GOPKXg_0[6];
NTI_7SQP9azfryP3zjoOAafzI6g_.size = sizeof(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g);
NTI_7SQP9azfryP3zjoOAafzI6g_.kind = 18;
NTI_7SQP9azfryP3zjoOAafzI6g_.base = 0;
NTI_7SQP9azfryP3zjoOAafzI6g_.flags = 3;
TM_aRNuFx1a6ph1klK2GOPKXg_10[0] = &TM_aRNuFx1a6ph1klK2GOPKXg_0[1];
TM_aRNuFx1a6ph1klK2GOPKXg_0[1].kind = 1;
TM_aRNuFx1a6ph1klK2GOPKXg_0[1].offset = offsetof(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g, x);
TM_aRNuFx1a6ph1klK2GOPKXg_0[1].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_aRNuFx1a6ph1klK2GOPKXg_0[1].name = "x";
TM_aRNuFx1a6ph1klK2GOPKXg_10[1] = &TM_aRNuFx1a6ph1klK2GOPKXg_0[2];
TM_aRNuFx1a6ph1klK2GOPKXg_0[2].kind = 1;
TM_aRNuFx1a6ph1klK2GOPKXg_0[2].offset = offsetof(tyObject_Vec2_7SQP9azfryP3zjoOAafzI6g, y);
TM_aRNuFx1a6ph1klK2GOPKXg_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_aRNuFx1a6ph1klK2GOPKXg_0[2].name = "y";
TM_aRNuFx1a6ph1klK2GOPKXg_0[0].len = 2; TM_aRNuFx1a6ph1klK2GOPKXg_0[0].kind = 2; TM_aRNuFx1a6ph1klK2GOPKXg_0[0].sons = &TM_aRNuFx1a6ph1klK2GOPKXg_10[0];
NTI_7SQP9azfryP3zjoOAafzI6g_.node = &TM_aRNuFx1a6ph1klK2GOPKXg_0[0];
NTI_St31Lu7mm4aIQTpxOCjvHA_.size = sizeof(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA);
NTI_St31Lu7mm4aIQTpxOCjvHA_.kind = 18;
NTI_St31Lu7mm4aIQTpxOCjvHA_.base = 0;
NTI_St31Lu7mm4aIQTpxOCjvHA_.flags = 3;
TM_aRNuFx1a6ph1klK2GOPKXg_11[0] = &TM_aRNuFx1a6ph1klK2GOPKXg_0[4];
TM_aRNuFx1a6ph1klK2GOPKXg_0[4].kind = 1;
TM_aRNuFx1a6ph1klK2GOPKXg_0[4].offset = offsetof(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA, x);
TM_aRNuFx1a6ph1klK2GOPKXg_0[4].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_aRNuFx1a6ph1klK2GOPKXg_0[4].name = "x";
TM_aRNuFx1a6ph1klK2GOPKXg_11[1] = &TM_aRNuFx1a6ph1klK2GOPKXg_0[5];
TM_aRNuFx1a6ph1klK2GOPKXg_0[5].kind = 1;
TM_aRNuFx1a6ph1klK2GOPKXg_0[5].offset = offsetof(tyObject_Vec2f_St31Lu7mm4aIQTpxOCjvHA, y);
TM_aRNuFx1a6ph1klK2GOPKXg_0[5].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_aRNuFx1a6ph1klK2GOPKXg_0[5].name = "y";
TM_aRNuFx1a6ph1klK2GOPKXg_0[3].len = 2; TM_aRNuFx1a6ph1klK2GOPKXg_0[3].kind = 2; TM_aRNuFx1a6ph1klK2GOPKXg_0[3].sons = &TM_aRNuFx1a6ph1klK2GOPKXg_11[0];
NTI_St31Lu7mm4aIQTpxOCjvHA_.node = &TM_aRNuFx1a6ph1klK2GOPKXg_0[3];
}

