const
    TILE_SIZE* = 32

    SCREEN_WIDTH_TILES* = 16
    SCREEN_HEIGHT_TILES* = 9

    SCREEN_WIDTH_PIXELS* = SCREEN_WIDTH_TILES * TILE_SIZE
    SCREEN_HEIGHT_PIXELS* = SCREEN_HEIGHT_TILES * TILE_SIZE
